import Link from "next/link";
import { ArrowLeft, Camera, PackageCheck } from "lucide-react";
import { SectionTitle } from "@/components/cliente/section-title";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/badge";
import { Timeline } from "@/components/ui/timeline";
import { getBoxCategory } from "@/lib/config/box-categories";
import { logisticsService } from "@/lib/services/logistics";
import { formatUsd } from "@/lib/utils/format";

export default async function BoxDetail({ params }: { params: Promise<{ codigo: string }> }) { const { codigo } = await params; const box = await logisticsService.getBoxByCode(codigo); if (!box) return <p>Caja no encontrada.</p>; const category = getBoxCategory(box.categoryId)!; return <><Link href="/cliente/cajas" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-navy-500"><ArrowLeft className="size-4" />Mis cajas</Link><SectionTitle eyebrow="Detalle de caja" title={box.code} action={<StatusBadge status={box.status} />} /><div className="mt-7 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid content-start gap-5"><Card className="shadow-none"><p className="text-xs font-bold uppercase tracking-wider text-navy-400">Categoría asignada</p><p className="mt-3 font-display text-3xl font-bold text-navy-950">{category.name}</p><p className="mt-1 font-display text-xl font-bold text-orange-600">{formatUsd(category.priceUsd)}</p><dl className="mt-5 grid grid-cols-2 gap-4 border-t border-stone-200 pt-5 text-sm"><div><dt className="text-navy-400">Medidas</dt><dd className="mt-1 font-semibold">{box.dimensions.length} × {box.dimensions.width} × {box.dimensions.height} in</dd></div><div><dt className="text-navy-400">Peso</dt><dd className="mt-1 font-semibold">{box.weightLb} lb</dd></div></dl></Card><Card className="shadow-none"><div className="flex items-center gap-3"><Camera className="size-5 text-orange-500" /><h2 className="font-display text-lg font-bold">Fotos de recepción</h2></div><div className="mt-4 grid grid-cols-2 gap-3">{[1,2].map((item) => <div key={item} className="grid aspect-[4/3] place-items-center rounded-2xl bg-cream-100 text-navy-300"><PackageCheck className="size-8" /><span className="sr-only">Foto mock {item}</span></div>)}</div></Card></div><Card className="shadow-none"><h2 className="font-display text-xl font-bold">Seguimiento</h2><div className="mt-6"><Timeline events={box.timeline} /></div></Card></div></>; }
