import Link from "next/link";
import { ArrowLeft, Box, Truck } from "lucide-react";
import { SectionTitle } from "@/components/cliente/section-title";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/badge";
import { Timeline } from "@/components/ui/timeline";
import { logisticsService } from "@/lib/services/logistics";

export default async function ShipmentDetail({ params }: { params: Promise<{ codigo: string }> }) { const { codigo } = await params; const [shipments, boxes] = await Promise.all([logisticsService.getShipments(), logisticsService.getBoxes()]); const shipment = shipments.find((item) => item.code === codigo); if (!shipment) return <p>Envío no encontrado.</p>; const shipmentBoxes = boxes.filter((box) => shipment.boxIds.includes(box.id)); return <><Link href="/cliente/envios" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-navy-500"><ArrowLeft className="size-4" />Mis envíos</Link><SectionTitle eyebrow="Detalle de envío" title={shipment.code} action={<StatusBadge status={shipment.status} />} /><div className="mt-7 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="grid content-start gap-5"><Card className="shadow-none"><div className="flex items-center gap-3"><Truck className="size-5 text-orange-500" /><div><p className="text-xs text-navy-400">Camión asignado</p><p className="font-bold text-navy-900">{shipment.truckId ?? "Pendiente"}</p></div></div><div className="mt-5 border-t border-stone-200 pt-5"><p className="text-xs text-navy-400">Destino</p><p className="mt-1 font-bold">{shipment.destinationCity}</p></div></Card><Card className="shadow-none"><h2 className="font-display text-lg font-bold">Cajas</h2><div className="mt-4 grid gap-3">{shipmentBoxes.map((box) => <div key={box.id} className="flex items-center justify-between rounded-xl bg-cream-100 p-3"><span className="flex items-center gap-2 text-sm font-bold"><Box className="size-4 text-orange-500" />{box.code}</span><StatusBadge status={box.status} /></div>)}</div></Card></div><Card className="shadow-none"><h2 className="font-display text-xl font-bold">Seguimiento</h2><div className="mt-6"><Timeline events={shipment.timeline} /></div></Card></div></>; }
