import { requireAdminUser } from "@/lib/auth/actions";
import Link from "@/components/admin/admin-access";
import { ArrowUpRight, Boxes, CircleDollarSign, MessageSquare, PackageCheck, Truck } from "lucide-react";
import { SectionTitle } from "@/components/cliente/section-title";
import { StatCard } from "@/components/ui/stat-card";
import { StatusBadge } from "@/components/ui/badge";
import { logisticsService } from "@/lib/services/logistics";
import { formatUsd } from "@/lib/utils/format";
import { invoiceTotal, isInvoiceOverdue } from "@/lib/utils/invoices";

export default async function AdminDashboard() { await requireAdminUser(["resumen"]);
  const [boxes,trucks,invoices,tickets]=await Promise.all([logisticsService.getBoxes(),logisticsService.getTrucks(),logisticsService.getInvoices(),logisticsService.getSupportTickets()]);
  const balance=invoices.filter(invoice=>!["pagada","borrador"].includes(invoice.status)).reduce((sum,invoice)=>sum+invoiceTotal(invoice),0);
  const shortcuts=[{label:"Pagos por revisar",value:invoices.filter(item=>item.status==="pago-reportado").length,href:"/admin/facturas",icon:CircleDollarSign},{label:"Consultas sin respuesta",value:tickets.filter(item=>item.status!=="cerrado"&&item.messages.at(-1)?.author==="cliente").length,href:"/admin/soporte",icon:MessageSquare},{label:"Cajas listas para entrega",value:boxes.filter(item=>item.status==="en-destino").length,href:"/admin/entregas",icon:PackageCheck}];
  return <><SectionTitle eyebrow="Operación A&L" title="Centro de control" description="Del ingreso en Miami a la última entrega. Prioridades, carga y clientes en una sola vista." action={<Link href="/admin/pendientes" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-brand-600 px-5 text-sm font-semibold text-white hover:bg-brand-700">Abrir pendientes<ArrowUpRight className="size-4" /></Link>} />
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Cajas en bodega" value={String(boxes.filter(box=>box.status==="en-bodega").length).padStart(2,"0")} icon={Boxes} /><StatCard label="Camiones activos" value={String(trucks.filter(truck=>truck.status!=="cerrado").length).padStart(2,"0")} icon={Truck} /><StatCard label="Entregadas" value={String(boxes.filter(box=>box.status==="entregada").length).padStart(2,"0")} icon={PackageCheck} /><StatCard label="Por cobrar" value={formatUsd(balance)} icon={CircleDollarSign} /></div>
    <section className="mt-6 rounded-2xl bg-navy-900 p-6 text-white sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/65">Atención del equipo</p><h2 className="mt-2 font-display text-2xl font-semibold">Lo que necesita avanzar hoy</h2></div><p className="text-sm text-white/75">{invoices.filter(invoice=>isInvoiceOverdue(invoice)).length} facturas vencidas</p></div><div className="mt-6 grid gap-3 md:grid-cols-3">{shortcuts.map(item=><Link key={item.href} href={item.href} className="rounded-xl border border-white/20 p-5 transition hover:bg-white/10"><div className="flex items-center justify-between"><item.icon className="size-5 text-white/75" /><ArrowUpRight className="size-4" /></div><p className="mt-5 font-display text-4xl font-semibold">{String(item.value).padStart(2,"0")}</p><h3 className="mt-2 text-sm text-white/85">{item.label}</h3></Link>)}</div></section>
    <section className="mt-6 rounded-2xl border border-line-300 bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-xl font-semibold text-navy-900">Guías máster recientes</h2><Link href="/admin/camiones" className="inline-flex min-h-11 items-center text-sm font-semibold text-brand-700">Ver todas</Link></div><div className="mt-4 grid gap-3">{trucks.slice(-6).reverse().map(truck=><Link key={truck.id} href={`/admin/camiones/${truck.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-cream-100 p-4 hover:bg-cream-50"><div><p className="font-semibold text-navy-900">{truck.code}</p><p className="mt-1 text-xs text-ink-500">{truck.route} · {truck.boxIds.length} cajas</p></div><StatusBadge status={truck.status} /></Link>)}{!trucks.length&&<p className="py-8 text-sm text-ink-500">Todavía no hay guías máster. Crea un camión para organizar la primera salida.</p>}</div></section>
  </>;
}
