import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { getStatusLabel } from "@/lib/config/status";
import { getBoxCategory } from "@/lib/config/box-categories";
import type { Invoice } from "@/lib/types";
import { invoiceSubtotal, invoiceTotal } from "@/lib/utils/invoices";
import { formatUsd } from "@/lib/utils/format";

const styles = StyleSheet.create({ page: { padding: 42, fontFamily: "Helvetica", color: "#1C2B4B", fontSize: 10 }, header: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 24, borderBottom: "1 solid #E3DED5" }, brand: { fontSize: 18, fontFamily: "Helvetica-Bold" }, orange: { color: "#E8621C" }, title: { fontSize: 28, fontFamily: "Helvetica-Bold", marginTop: 30 }, meta: { marginTop: 8, color: "#5A6680" }, table: { marginTop: 30 }, row: { flexDirection: "row", borderBottom: "1 solid #E3DED5", paddingVertical: 10 }, cellMain: { width: "50%" }, cell: { width: "16.6%", textAlign: "right" }, totalBox: { marginTop: 25, marginLeft: "55%" }, totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5 }, grand: { marginTop: 6, paddingTop: 10, borderTop: "2 solid #1C2B4B", fontFamily: "Helvetica-Bold", fontSize: 13 }, note: { marginTop: 45, padding: 16, backgroundColor: "#F6F1E9", color: "#5A6680", lineHeight: 1.6 } });

export function InvoiceDocument({ invoice }: { invoice: Invoice }) { return <Document title={`Factura ${invoice.number}`}><Page size="LETTER" style={styles.page}><View style={styles.header}><Text style={styles.brand}>A&L <Text style={styles.orange}>Trucking Logistics</Text></Text><Text>USA → México</Text></View><Text style={styles.title}>Factura</Text><Text style={styles.meta}>{invoice.number} · Estado: {getStatusLabel(invoice.status)}</Text><View style={styles.table}><View style={styles.row}><Text style={styles.cellMain}>Categoría</Text><Text style={styles.cell}>Cantidad</Text><Text style={styles.cell}>Precio</Text><Text style={styles.cell}>Importe</Text></View>{invoice.lines.map((line, lineIndex) => <View key={`${line.categoryId}-${line.unitPriceUsd}-${lineIndex}`} style={styles.row}><Text style={styles.cellMain}>{line.categoryName ?? getBoxCategory(line.categoryId)?.name ?? line.categoryId}{line.description ? ` — ${line.description}` : ""}</Text><Text style={styles.cell}>{line.quantity}</Text><Text style={styles.cell}>{formatUsd(line.unitPriceUsd)}</Text><Text style={styles.cell}>{formatUsd(line.quantity * line.unitPriceUsd)}</Text></View>)}</View><View style={styles.totalBox}><View style={styles.totalRow}><Text>Subtotal</Text><Text>{formatUsd(invoiceSubtotal(invoice))}</Text></View><View style={styles.totalRow}><Text>Recargo por excedente</Text><Text>{formatUsd(invoice.excessFeeUsd ?? 0)}</Text></View><View style={styles.totalRow}><Text>Seguro</Text><Text>{formatUsd(invoice.insuranceUsd)}</Text></View><View style={styles.totalRow}><Text>Entrega</Text><Text>{formatUsd(invoice.homeDeliveryUsd)}</Text></View><View style={[styles.totalRow, styles.grand]}><Text>Total</Text><Text>{formatUsd(invoiceTotal(invoice))}</Text></View></View><Text style={styles.note}>Documento operativo de cobro. No sustituye un comprobante fiscal. Los pagos están sujetos a validación por A&L.</Text></Page></Document>; }
