/* React PDF Image embeds a PDF asset, not an HTML image. */
/* eslint-disable jsx-a11y/alt-text */
import {formatDimensions} from "@/lib/utils/format";
import {Document,Image,Page,StyleSheet,Text,View} from "@react-pdf/renderer";
import {truckLoad} from "@/lib/utils/truck-load";
import type {Box,Recipient,Shipment,Truck,User,Warehouse} from "@/lib/types";
const s=StyleSheet.create({
 page:{paddingTop:82,paddingBottom:48,paddingHorizontal:32,fontFamily:"Helvetica",fontSize:8,color:"#172338"},
 header:{position:"absolute",bottom:722,left:32,right:32,height:46,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:2,paddingBottom:10},
 logo:{width:86,height:34,objectFit:"contain"},title:{fontSize:17,fontFamily:"Helvetica-Bold"},sub:{fontSize:7,color:"#526174",marginTop:5},
 row:{flexDirection:"row",borderBottomWidth:0.5,borderColor:"#aab0b8"},half:{width:"50%",padding:8,borderWidth:0.5,borderColor:"#aab0b8"},label:{fontFamily:"Helvetica-Bold",fontSize:8,marginBottom:4},
 section:{backgroundColor:"#e8ebef",padding:6,fontFamily:"Helvetica-Bold",fontSize:9,marginTop:12},cell:{padding:6},number:{fontFamily:"Helvetica-Bold",fontSize:14},
 total:{flexDirection:"row",justifyContent:"space-between",backgroundColor:"#f4f5f7",padding:10,marginTop:10},footer:{position:"absolute",bottom:20,left:32,right:32,fontSize:7,color:"#526174",flexDirection:"row",justifyContent:"space-between"},
 note:{fontSize:7,color:"#526174",marginTop:6},signature:{width:"48%",borderTopWidth:0.5,paddingTop:5,marginTop:28}
});
const number=(n:number)=>n.toLocaleString("en-US",{maximumFractionDigits:2});
const text=(v:string|undefined)=>v?(v.length>300?v.slice(0,297)+"...":v):"No registrado / Not recorded";
export function ManifestDocument({truck,boxes,users,shipments,recipients,warehouses=[],logoSrc,generatedAt=new Date().toISOString()}:{truck:Truck;boxes:Box[];users:User[];shipments:Shipment[];recipients:Recipient[];warehouses?:Warehouse[];logoSrc?:string;generatedAt?:string}){
 const load=truckLoad(boxes),origin=warehouses.find(w=>w.id===truck.originWarehouseId),draft=["planificado","cargando"].includes(truck.status);
 return <Document title={"Bill of Lading "+truck.code} author="A&L Trucking Logistics"><Page size="LETTER" style={s.page}>
 <View style={s.row} wrap={false}><View style={s.half}><Text style={s.label}>SHIP FROM / ORIGEN</Text><Text>{text(origin?.name??truck.originWarehouseName)}</Text><Text>{text(origin?.address)}</Text><Text>{[origin?.city,origin?.country].filter(Boolean).join(" · ")}</Text></View><View style={s.half}><Text style={s.label}>BOL NUMBER: {truck.code}</Text><Text>Carrier: A&L TRUCKING LOGISTICS</Text><Text>Unidad / placa: {truck.plate}</Text><Text>Chofer: {text(truck.driverName)}</Text><Text>Salida programada: {truck.departureDate}</Text><Text>Generado UTC: {generatedAt.slice(0,19).replace("T"," ")}</Text></View></View>
 <View style={s.total} wrap={false}><View><Text>PACKAGES / PIEZAS</Text><Text style={s.number}>{load.count}</Text></View><View><Text>ACTUAL WEIGHT / PESO REAL</Text><Text style={s.number}>{number(load.weightLb)} lb</Text></View><View><Text>VOLUME / VOLUMEN</Text><Text style={s.number}>{number(load.volumeFt3)} ft³</Text><Text>{number(load.volumeM3)} m³</Text></View></View>
 <Text style={s.note}>Volumen exterior sumado, sin huecos de estiba. Peso real, no dimensional de cobro. {truck.maxWeightLb?"Límite configurado: "+number(truck.maxWeightLb)+" lb.":"Sin límite de peso configurado."}</Text>
 <Text style={s.section} minPresenceAhead={55}>SHIP TO / DESTINOS Y LLEGADAS ESTIMADAS</Text>
 {truck.stops?.length?truck.stops.map((stop,index)=>{const w=warehouses.find(w=>w.id===stop.warehouseId),cargo=truckLoad(boxes.filter(b=>b.destinationWarehouseId===stop.warehouseId));return <View key={stop.warehouseId} style={s.row} wrap={false}><View style={[s.cell,{width:"72%"}]}><Text style={s.label}>{index+1}. {text(w?.name??stop.city)}</Text><Text>{text(w?.address)}</Text><Text>{stop.city} · ETA: {stop.arrivalDate}</Text></View><View style={[s.cell,{width:"28%"}]}><Text>{cargo.count} piezas · {number(cargo.weightLb)} lb</Text><Text>{number(cargo.volumeFt3)} ft³</Text></View></View>;}):<Text style={s.cell}>{truck.destinationCity} · Sin paradas de almacén registradas.</Text>}
 {boxes.some(b=>!b.destinationWarehouseId)&&<Text style={s.note}>{boxes.filter(b=>!b.destinationWarehouseId).length} piezas sin almacén de destino asignado.</Text>}
 <Text style={s.section} minPresenceAhead={40}>SPECIAL INSTRUCTIONS / INSTRUCCIONES</Text><Text style={s.cell}>{text(truck.notes)}</Text>
 <View style={s.row} wrap={false}><View style={s.half}><Text style={s.label}>THIRD PARTY BILL TO / FACTURAR A TERCERO</Text><Text>________________________________________</Text></View><View style={s.half}><Text style={s.label}>FREIGHT TERMS / CONDICIONES DEL FLETE</Text><Text>Prepaid [ ]    Collect [ ]    Third party [ ]</Text><Text style={s.note}>Completar y confirmar. No se deduce de pagos de clientes.</Text></View></View>
 <Text style={s.section} minPresenceAhead={65}>CUSTOMER ORDER & CARRIER INFORMATION / DETALLE</Text><Text style={s.note}>Una fila por pieza física. Descripción registrada, no clasificación de mercancía peligrosa ni NMFC.</Text>
 <View style={s.row} wrap={false}><Text style={[s.cell,{width:"20%"}]}>Código / pieza</Text><Text style={[s.cell,{width:"30%"}]}>Cliente / descripción</Text><Text style={[s.cell,{width:"28%"}]}>Destinatario / parada</Text><Text style={[s.cell,{width:"22%"}]}>Peso / medidas / volumen</Text></View>
 {boxes.map(box=>{const user=users.find(u=>u.id===box.userId),shipment=shipments.find(sh=>sh.id===box.shipmentId),recipient=shipment?.recipientSnapshot??box.recipientSnapshot??recipients.find(r=>r.id===(shipment?.recipientId??box.recipientId)&&r.userId===box.userId),destination=warehouses.find(w=>w.id===box.destinationWarehouseId);return <View key={box.id} style={s.row} wrap={false}><View style={[s.cell,{width:"20%"}]}><Text style={s.label}>{box.code}</Text><Text>Pieza {box.receptionGroup?box.receptionGroup.index+"/"+box.receptionGroup.total:"1/1"}</Text><Text>{shipment?.code??"Sin guía individual"}</Text></View><View style={[s.cell,{width:"30%"}]}><Text>{text(user?user.firstName+" "+user.paternalLastName:undefined)}</Text><Text>{user?.lockerCode}</Text><Text>{text(box.prealertDetails?.description??box.categoryName??box.categoryId)}</Text></View><View style={[s.cell,{width:"28%"}]}><Text>{text(recipient?.name)}</Text><Text>{recipient?.phone??""}</Text><Text>{text(destination?.name)}</Text></View><View style={[s.cell,{width:"22%"}]}><Text style={s.label}>{number(box.weightLb)} lb</Text><Text>{formatDimensions(box.dimensions)}</Text><Text>{number(truckLoad([box]).volumeFt3)} ft³</Text></View></View>;})}
 {!boxes.length&&<Text style={s.cell}>Sin carga registrada. Este documento no acredita recepción de mercancía.</Text>}
 <View wrap={false}><View style={s.total}><Text style={s.label}>GRAND TOTAL</Text><Text>{load.count} piezas · {number(load.weightLb)} lb · {number(load.volumeFt3)} ft³</Text></View>{load.missingDimensions>0&&<Text style={s.note}>Volumen parcial: {load.missingDimensions} pieza(s) sin medidas registradas. El peso real incluye todas las piezas.</Text>}<Text style={s.section}>VERIFICACIÓN Y FIRMAS / VERIFICATION & SIGNATURES</Text><Text style={s.note}>SCAC: ______________    NMFC / Class: ______________    COD: ______________</Text><Text style={s.note}>Datos sujetos a confirmación del transportista. Este formato operativo no certifica clasificación, seguridad de carga ni condiciones legales. Completar firmas después de verificar la carga.</Text><View style={{flexDirection:"row",justifyContent:"space-between"}}><View style={s.signature}><Text>Remitente / Shipper - Firma y fecha</Text></View><View style={s.signature}><Text>Transportista / Carrier - Firma y fecha</Text></View></View></View>
 <View fixed style={s.header}/>{logoSrc?<Image fixed src={logoSrc} style={[s.logo,{position:"absolute",bottom:734,left:32}]}/>:<Text fixed style={{position:"absolute",bottom:750,left:32}}>A&L TRUCKING LOGISTICS</Text>}<Text fixed style={[s.title,{position:"absolute",bottom:747,right:32}]}>BILL OF LADING</Text><Text fixed style={[s.sub,{position:"absolute",bottom:735,right:32}]} render={()=>truck.code+" · "+(draft?"BORRADOR / DRAFT":"REGISTRO OPERATIVO")}/>
 <View style={s.footer} fixed><Text>{truck.code} · A&L · Carga registrada al generar esta copia</Text><Text render={({pageNumber,totalPages})=>"Página "+pageNumber+" de "+totalPages}/></View>
 </Page></Document>;
}
