/* React PDF Image is an embedded PDF asset, not an HTML image. */
/* eslint-disable jsx-a11y/alt-text */
import {readFileSync} from 'node:fs';
import {Document,Image,Page,StyleSheet,Text,View} from '@react-pdf/renderer';
import type {Box,Invoice} from '@/lib/types';
import {invoiceTotal} from '@/lib/utils/invoices';
import {getStatusLabel} from '@/lib/config/status';
const s=StyleSheet.create({page:{padding:12,fontFamily:'Helvetica',fontSize:9,color:'#111',lineHeight:1.4},logo:{width:105,height:43,objectFit:'contain',alignSelf:'center',marginBottom:8},title:{fontFamily:'Helvetica-Bold',fontSize:13,textAlign:'center'},center:{textAlign:'center',marginBottom:5},section:{borderTopWidth:0.5,borderColor:'#888',paddingTop:8,marginTop:8},bold:{fontFamily:'Helvetica-Bold'},row:{flexDirection:'row',justifyContent:'space-between',gap:6,marginTop:3},amount:{fontFamily:'Helvetica-Bold',textAlign:'right'},small:{fontSize:8},total:{fontSize:13,fontFamily:'Helvetica-Bold',marginTop:8},note:{fontSize:8,marginTop:12,textAlign:'center'}});
const usd=(n:number)=>`USD ${n.toFixed(2)}`;
export function ThermalDocument({reference,invoices,boxes=[],logoPath,receipt=false}:{reference:string;invoices:Invoice[];boxes?:Box[];logoPath:string;receipt?:boolean}){
 const total=invoices.reduce((n,i)=>n+invoiceTotal(i),0);
 const pending=invoices.filter(i=>i.status!=='pagada').reduce((n,i)=>n+invoiceTotal(i),0);
 const estimate=boxes.filter(b=>b.status!=='rechazada').reduce((n,b)=>n+(b.billing?.amountUsd??b.customPriceUsd??0)+(b.excessFeeUsd??0),0);
 return <Document title={`${receipt?'Recibo':'Factura'} ${reference}`}><Page size={{width:80*72/25.4}} wrap={false} style={s.page}>
 <Image src={{data:readFileSync(logoPath),format:"png"}} style={s.logo}/><Text style={s.title}>{receipt?'RECIBO DE RECEPCIÓN':'FACTURA - VOUCHER'}</Text><Text style={[s.center,s.bold]}>{reference}</Text>
 <Text style={s.center}>{(boxes[0]?.receivedAt??invoices[0]?.issuedAt??'').slice(0,10)}</Text>
 {boxes.length>0&&<View style={s.section}><Text style={s.bold}>{boxes.length} unidad(es) recibida(s)</Text>{boxes[0].originWarehouseName&&<Text>Origen: {boxes[0].originWarehouseName}</Text>}{boxes[0].recipientSnapshot&&<Text>Destinatario: {boxes[0].recipientSnapshot.name} / {boxes[0].recipientSnapshot.phone}</Text>}{boxes.map((b,index)=><View key={b.id} style={{marginTop:7}} wrap={false}><Text style={s.bold}>{index+1}/{boxes.length} - {b.code}</Text><Text>{b.dimensions.length} x {b.dimensions.width} x {b.dimensions.height} in / {b.weightLb} lb</Text><Text>{getStatusLabel(b.status)}</Text></View>)}</View>}
 {invoices.map(i=><View key={i.id} style={s.section}><Text style={s.bold}>{i.number}</Text><Text>Estado: {getStatusLabel(i.status)}</Text>{i.lines.map((l,index)=><View key={index} style={{marginTop:7}} wrap={false}><Text>{l.categoryName??l.categoryId}</Text>{l.description&&<Text style={s.small}>{l.description}</Text>}<View style={s.row}><Text>{l.quantity} x {usd(l.unitPriceUsd)}</Text><Text style={s.amount}>{usd(l.quantity*l.unitPriceUsd)}</Text></View></View>)}{[['Recargo',i.excessFeeUsd??0],['Seguro',i.insuranceUsd],['Entrega',i.homeDeliveryUsd]].map(([label,value])=>Number(value)>0&&<View key={String(label)} style={s.row}><Text>{label}</Text><Text>{usd(Number(value))}</Text></View>)}<View style={s.row}><Text style={s.bold}>Total factura</Text><Text style={s.amount}>{usd(invoiceTotal(i))}</Text></View>{i.payments?.map(p=><View key={p.folio} style={{marginTop:6}} wrap={false}><Text style={s.small}>Folio: {p.folio}</Text><Text style={s.small}>{p.method} - {p.status} - {usd(p.amountUsd)}</Text>{p.externalReference&&<Text style={s.small}>Referencia: {p.externalReference}</Text>}<Text style={s.small}>{p.recordedAt.slice(0,10)} / {p.warehouseName??'Sin ubicación'} / {p.actorName}</Text></View>)}</View>)}
 <View style={s.section} wrap={false}><View style={s.row}><Text style={s.total}>{invoices.length?'TOTAL':'ESTIMADO'}</Text><Text style={s.total}>{usd(invoices.length?total:estimate)}</Text></View>{invoices.length>0?<><Text>Pendiente de pago: {usd(pending)}</Text><Text style={s.bold}>{invoices.every(i=>i.status==='pagada')?'PAGO CONFIRMADO':invoices.some(i=>i.status==='pendiente-pago-destino')?'PENDIENTE DE PAGO EN DESTINO':'CONSULTA EL ESTADO DE LAS FACTURAS'}</Text></>:<Text>Importe estimado de recepción. Consulta facturas y pagos en el panel; este recibo no acredita un pago.</Text>}</View>
 <Text style={s.note}>Documento operativo. No sustituye un comprobante fiscal. Solo los pagos confirmados acreditan dinero recibido.</Text><Text style={s.note}>A&L Trucking Logistics</Text>
 </Page></Document>;
}
