"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {Trash2,ShieldAlert} from "lucide-react";
import {getDeletionDirectory,previewDeletion,deleteTestRecord} from "@/lib/auth/deletion-actions";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog} from "@/components/ui/dialog";
type Data=Awaited<ReturnType<typeof getDeletionDirectory>>;
type Row=Data["orders"][number]|Data["people"][number];
type Preview=Awaited<ReturnType<typeof previewDeletion>>;
export function DeletionManager({data}:{data:Data}){
 const router=useRouter(),[tab,setTab]=useState<"orders"|"people">("orders"),[query,setQuery]=useState(""),[page,setPage]=useState(0),[selected,setSelected]=useState<Row|null>(null),[preview,setPreview]=useState<Preview|null>(null),[confirmation,setConfirmation]=useState(""),[testData,setTestData]=useState(false),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[pending,start]=useTransition();
 const rows=data[tab].filter(r=>(r.reference+" "+r.name+" "+r.detail).toLowerCase().includes(query.trim().toLowerCase())),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages-1);
 function choose(row:Row){setSelected(row);setPreview(null);setMessage("");setConfirmation("");setReason("");setTestData(false);start(async()=>{try{setPreview(await previewDeletion({kind:row.kind,id:row.id}));}catch{setPreview({ok:false,error:"No se pudo consultar el alcance. Revisa tu conexión y acceso."});}});}
 function remove(){if(!selected||!preview?.ok)return;start(async()=>{try{const result=await deleteTestRecord({kind:selected.kind,id:selected.id,revision:preview.revision,confirmation,testData,reason});if(!result.ok){setMessage(result.error);return;}setSelected(null);setMessage(result.message);router.refresh();}catch{setMessage("No se confirmó la eliminación. Actualiza la lista antes de volver a intentarlo.");}});}
 return <section className="mt-6 space-y-5">
  <div className="flex gap-3 rounded-2xl border border-orange-200 bg-orange-50 p-5 text-sm leading-6"><ShieldAlert className="mt-1 size-5 shrink-0 text-orange-700"/><p>Exclusivo del administrador completo. No borra cargos de Clover ni ejecuta reembolsos. Se conserva respaldo de auditoría; los archivos asociados dejan de estar disponibles. Para eliminar un usuario, retira primero sus órdenes.</p></div>
  {!selected&&message&&<p role="status" className="rounded-xl border border-line-300 bg-white p-4 text-sm">{message}</p>}
  <div className="rounded-2xl border border-line-300 bg-white p-5"><div className="mb-5 flex gap-2">{(["orders","people"] as const).map(key=><Button key={key} variant={tab===key?"primary":"ghost"} onClick={()=>{setTab(key);setPage(0);setQuery("");}}>{key==="orders"?"Órdenes y recepciones":"Usuarios"}</Button>)}</div><Input label="Buscar registro" placeholder="Código, nombre o correo" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/>
   <div className="mt-5 divide-y divide-line-300">{rows.slice(current*10,current*10+10).map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div className="min-w-0"><h2 className="break-all font-semibold">{row.reference}</h2><p className="mt-1 text-sm text-navy-500">{row.name} · {row.detail}</p></div><Button variant="destructive" disabled={pending} onClick={()=>choose(row)}><Trash2 className="size-4"/>Revisar eliminación</Button></article>)}</div>
   {!rows.length&&<p className="py-12 text-center text-sm text-navy-500">No hay registros con estos filtros.</p>}
   <div className="flex flex-wrap items-center justify-between gap-3 border-t border-line-300 pt-4"><span className="text-xs text-navy-500">{rows.length} registros · Página {current+1} de {pages}</span><div className="flex gap-2"><Button variant="ghost" disabled={current===0} onClick={()=>setPage(current-1)}>Anterior</Button><Button variant="ghost" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Siguiente</Button></div></div>
  </div>
  <Dialog open={!!selected} onClose={()=>{if(!pending)setSelected(null);}} title="Revisar eliminación" description={selected?.reference}>
   <div className="grid max-h-[65vh] gap-4 overflow-y-auto">{!preview?<p role="status">Revisando relaciones…</p>:!preview.ok?<p role="alert" className="text-sm text-red-700">{preview.error}</p>:<><dl className="grid grid-cols-2 gap-3 rounded-xl bg-cream-100 p-4 text-sm">{Object.entries({Paquetes:preview.counts.packages,Facturas:preview.counts.invoices,Envíos:preview.counts.shipments,"Camiones afectados":preview.counts.trucks,Usuarios:preview.counts.users}).map(([label,count])=><div key={label}><dt className="text-xs text-navy-500">{label}</dt><dd className="mt-1 font-semibold">{count}</dd></div>)}</dl>{preview.paidInvoices>0&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">Incluye {preview.paidInvoices} factura(s) marcada(s) pagada(s). Solo confirma si los pagos también son de prueba. No se devolverá dinero.</p>}<Input label="Motivo de la eliminación" value={reason} maxLength={500} disabled={pending} onChange={e=>setReason(e.target.value)}/><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 size-4 shrink-0 accent-orange-600" type="checkbox" checked={testData} disabled={pending} onChange={e=>setTestData(e.target.checked)}/>Confirmo que estos registros son datos de prueba y revisé los documentos relacionados.</label><Input label="Escribe ELIMINAR para confirmar" autoComplete="off" value={confirmation} disabled={pending} onChange={e=>setConfirmation(e.target.value)}/></>}{message&&<p role="alert" className="text-sm text-red-700">{message}</p>}<div className="flex justify-end gap-3"><Button variant="ghost" disabled={pending} onClick={()=>setSelected(null)}>Cancelar</Button>{preview?.ok&&<Button variant="destructive" loading={pending} disabled={confirmation!=="ELIMINAR"||!testData||reason.trim().length<5} onClick={remove}>Eliminar registros</Button>}</div></div>
  </Dialog>
 </section>;
}
