"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { getDestinationDesk, scanUnload } from "@/lib/auth/warehouse-actions";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/badge";
type Data=Awaited<ReturnType<typeof getDestinationDesk>>;
export function DestinationDesk({data}:{data:Data}){
 const router=useRouter(),scanner=useRef<HTMLInputElement>(null);
 const [warehouseId,setWarehouse]=useState(data.warehouses[0]?.id??""),[truckId,setTruck]=useState(""),[code,setCode]=useState(""),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const warehouse=data.warehouses.find(w=>w.id===warehouseId),trucks=data.trucks.filter(t=>t.stops.some(s=>s.warehouseId===warehouseId)),packages=data.boxes.filter(b=>b.warehouseId===warehouseId&&(!truckId||b.truckId===truckId)),shown=packages.filter(b=>[b.code,b.originTracking,b.customer?.name,b.customer?.phone].some(v=>v?.toLowerCase().includes(search.toLowerCase())));
 return <div className="grid gap-6"><section className="rounded-3xl bg-navy-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-400">Recepción física · Escaneo de descarga</p><h2 className="mt-2 font-display text-2xl font-bold">Cada paquete, confirmado en su destino.</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><Select tone="dark" label="Almacén" value={warehouseId} options={[{value:"",label:"Selecciona almacén"},...data.warehouses.map(w=>({value:w.id,label:`${w.name} · ${w.city}`}))]} onChange={e=>{setWarehouse(e.target.value);setTruck("");setMessage("");}}/><Select tone="dark" label="Camión / viaje" value={truckId} options={[{value:"",label:"Selecciona viaje"},...trucks.map(t=>({value:t.id,label:`${t.code} · ${t.plate} · ${t.stops.find(s=>s.warehouseId===warehouseId)?.arrivalDate}`}))]} onChange={e=>{setTruck(e.target.value);setMessage("");}}/></div>
 <form className="mt-5 flex flex-wrap items-end gap-3" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const result=await scanUnload(truckId,warehouseId,code);setMessage(result.ok?result.message:result.error);if(result.ok){setCode("");router.refresh();}}catch{setMessage("No se pudo confirmar la descarga. Reintenta el mismo código para comprobar su estado.");}finally{setBusy(false);scanner.current?.focus();}}}><div className="min-w-60 flex-1"><Input ref={scanner} tone="dark" label="Escanea el código del paquete" placeholder="BX-…" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} disabled={!warehouse?.canReceive} required/></div><Button type="submit" disabled={!warehouse?.canReceive||!truckId} loading={busy}>Confirmar descarga</Button></form><p className="mt-3 text-sm text-white/60">Lector USB o Bluetooth en modo teclado + Enter. El evento se registra únicamente al confirmar cada código.</p>{warehouse&&!warehouse.canReceive&&<p className="mt-3 text-orange-300">Tu acceso a este almacén es de consulta; no puedes registrar descargas.</p>}<p role="status" aria-live="polite" className="mt-4 font-semibold">{message}</p></section>
 {!data.warehouses.length&&<p className="rounded-2xl border border-stone-200 bg-white p-6">No tienes almacenes activos asignados. Solicita al administrador que configure tu acceso.</p>}
 <div className="flex flex-wrap items-center justify-between gap-4"><p className="font-semibold">{packages.filter(b=>b.receivedAt).length} recibidos / {packages.length} paquetes</p><Input label="Buscar paquete o cliente" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="grid gap-3">{shown.slice(0,100).map(b=><article key={b.id} className="rounded-2xl border border-stone-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-display text-lg font-bold">{b.code}</h3><StatusBadge status={b.status}/></div><p className="mt-2 text-sm text-navy-500">{b.dimensions.length} × {b.dimensions.width} × {b.dimensions.height} pulgadas · {b.weightLb} lb{b.originTracking?` · Tracking ${b.originTracking}`:""}</p>{b.customer&&<details className="mt-4"><summary className="cursor-pointer font-semibold text-orange-700">Contacto del cliente · {b.customer.name}</summary><div className="mt-3 flex flex-wrap gap-5 text-sm"><span>Casillero {b.customer.lockerCode}</span><a href={`tel:${b.customer.phone}`}>{b.customer.phone}</a><a href={`mailto:${b.customer.email}`}>{b.customer.email}</a></div></details>}{b.receivedAt&&<p className="mt-3 text-xs text-emerald-700">Descarga registrada: {new Date(b.receivedAt).toLocaleString("es")}</p>}</article>)}</div>{shown.length>100&&<p className="text-sm">Se muestran 100 resultados. Refina la búsqueda para encontrar un paquete.</p>}
 </div>;
}
