"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { checkEmailProvider, sendProviderTest } from "@/lib/auth/email-actions";

export function EmailControls({keyPresent,from,mode,webhook,site}:{keyPresent:boolean;from:string;mode:string;webhook:boolean;site:string}) {
  const [sender,setSender]=useState(from.match(/<([^>]+)>/)?.[1]??from);
  const [to,setTo]=useState("");const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  return <section className="mt-6 rounded-xl border border-line-300 bg-white p-6"><h2 className="font-display text-xl font-bold">Conexión y prueba real</h2><div className="my-5 grid gap-3 text-sm text-ink-700 sm:grid-cols-2"><p>Clave privada: {keyPresent?"Configurada":"Pendiente"}</p><p>Modo operativo: {mode}</p><p>Webhook: {webhook?"Configurado; validar recepción":"Pendiente"}</p><p className="break-all">URL de enlaces: {site}</p></div><p className="mb-5 text-sm leading-6 text-ink-500">La prueba envía solo un correo al destinatario indicado. No vacía la cola ni activa envíos masivos. Un sitio localhost y su logo solo son accesibles desde este equipo; para clientes externos se necesita una URL pública.</p><Button variant="secondary" disabled={!keyPresent} loading={busy} onClick={async()=>{setBusy(true);try{const result=await checkEmailProvider();setMessage(result.ok?result.domains.map(d=>`${d.name}: ${d.status}`).join(" · ")||"No hay dominios registrados.":result.error);}catch{setMessage("La consulta no pudo completarse.");}finally{setBusy(false);}}}>Comprobar dominios en Resend</Button><form className="mt-6 grid gap-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await sendProviderTest({from:sender,to,confirmed});setMessage(result.ok?result.message:result.error);}catch{setMessage("No se pudo confirmar la prueba. Revisa el estado antes de repetirla.");}finally{setBusy(false);}}}><div className="grid gap-4 sm:grid-cols-2"><Input label="Correo remitente de la prueba" type="email" required value={sender} onChange={e=>setSender(e.target.value)}/><Input label="Destinatario autorizado para la prueba" type="email" required value={to} onChange={e=>setTo(e.target.value)}/></div><label className="flex min-h-11 items-center gap-3 text-sm text-ink-700"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>Autorizo enviar un correo real a esta dirección.</label><Button type="submit" loading={busy} disabled={!keyPresent||!confirmed} className="justify-self-start">Enviar prueba real</Button></form>{message&&<p role="status" className="mt-5 rounded-lg bg-cream-100 p-4 text-sm leading-6">{message}</p>}<p className="mt-5 text-xs leading-6 text-ink-500">Para activar la operación: configurar RESEND_FROM_EMAIL, EMAIL_DELIVERY=resend y una URL pública en el servidor, comprobar el webhook e iniciar el worker. La clave nunca se muestra ni se guarda en el navegador.</p></section>;
}
