"use client";
import { useState, type ReactNode } from "react";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export type DirectoryRow={id:string;title:string;detail:string;search:string;active:boolean;kind?:string;extra?:ReactNode};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export function LocationDirectory({title,description,rows,onEdit,onCreate,createLabel,locations=false}:{title:string;description:string;rows:DirectoryRow[];onEdit:(id:string)=>void;onCreate:()=>void;createLabel:string;locations?:boolean}){
  const [query,setQuery]=useState(""),[kind,setKind]=useState("todos"),[status,setStatus]=useState("todos"),[page,setPage]=useState(1);
  const found=rows.filter(r=>normalize(r.search).includes(normalize(query.trim()))&&(kind==="todos"||r.kind===kind||(kind!=="ambos"&&r.kind==="ambos"))&&(status==="todos"||r.active===(status==="activos"))).sort((a,b)=>a.title.localeCompare(b.title,"es",{numeric:true}));
  const pages=Math.max(1,Math.ceil(found.length/12)),current=Math.min(page,pages),start=(current-1)*12;
  return <section className="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-stone-100 p-5 sm:p-6"><div><p className="mb-1 text-xs font-bold uppercase tracking-widest text-orange-700">{rows.length} {locations?"ubicaciones":"operadores"} · directorio</p><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-2 max-w-3xl text-sm text-navy-500">{description}</p></div><Button onClick={onCreate}>{createLabel}</Button></header>
    <div className="grid gap-3 bg-stone-50 p-5 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr]"><Input label={locations?"Buscar almacenes":"Buscar operadores"} placeholder={locations?"Nombre, ciudad, estado o dirección…":"Nombre, correo o almacén…"} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>{locations&&<Select label="Tipo de ubicación" value={kind} options={[{value:"todos",label:"Todos los tipos"},{value:"origen",label:"Origen (incluye ambos)"},{value:"destino",label:"Destino (incluye ambos)"},{value:"ambos",label:"Solo origen y destino"}]} onChange={e=>{setKind(e.target.value);setPage(1);}}/>}<Select label="Estado del registro" value={status} options={[{value:"todos",label:"Activos e inactivos"},{value:"activos",label:"Solo activos"},{value:"inactivos",label:"Solo inactivos"}]} onChange={e=>{setStatus(e.target.value);setPage(1);}}/></div>
    <div className="divide-y divide-stone-100">{found.slice(start,start+12).map(r=><article key={r.id} className="flex flex-wrap items-center gap-4 px-5 py-4 transition hover:bg-orange-50/40 sm:px-6"><div className="min-w-0 flex-1 basis-64"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-navy-950">{r.title}</h3>{r.kind&&<span className="rounded-md bg-navy-50 px-2 py-1 text-xs font-semibold text-navy-700">{r.kind==="ambos"?"Origen y destino":r.kind==="origen"?"Origen":"Destino"}</span>}<span className={`rounded-md px-2 py-1 text-xs ${r.active?"bg-emerald-50 text-emerald-800":"bg-stone-100 text-stone-600"}`}>{r.active?"Activo":"Inactivo"}</span></div><p className="mt-1 break-words text-sm text-navy-500">{r.detail}</p>{r.extra}</div><Button variant="secondary" aria-label={`Editar ${r.title}`} onClick={()=>onEdit(r.id)}>Editar</Button></article>)}</div>
    {!found.length&&<div className="p-10 text-center"><p className="font-semibold">{rows.length?"No hay coincidencias":"Todavía no hay registros"}</p><p className="mt-2 text-sm text-navy-500">{rows.length?"Prueba otro término o cambia los filtros.":"Usa el botón de crear para agregar el primero."}</p>{rows.length>0&&<Button variant="ghost" onClick={()=>{setQuery("");setKind("todos");setStatus("todos");setPage(1);}}>Limpiar filtros</Button>}</div>}
    <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-100 px-5 py-4 text-sm"><span role="status">{found.length?`${start+1}–${Math.min(start+12,found.length)} de ${found.length}`:"0 resultados"}</span><div className="flex items-center gap-3"><Button variant="secondary" aria-label={`Página anterior de ${title}`} disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><span>{current} / {pages}</span><Button variant="secondary" aria-label={`Página siguiente de ${title}`} disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente</Button></div></footer>
  </section>;
}
