"use client";
import { useEffect, useRef } from "react";
import Image from "next/image";
import JsBarcode from "jsbarcode";
import logo from "../../../public/brand/logoayl.png";
import type { Dimensions } from "@/lib/config/box-categories";
export function PackageLabel({code,dimensions,weightLb,lockerCode,position="1/1",receptionCode,recipient,controls=true}:{code:string;dimensions:Dimensions;weightLb:number;lockerCode:string;position?:string;receptionCode?:string;recipient?:{name:string;phone:string};controls?:boolean}){
 const barcode=useRef<SVGSVGElement>(null);
 useEffect(()=>{if(barcode.current)JsBarcode(barcode.current,code,{format:"CODE128",width:2,height:85,margin:20,displayValue:false});},[code]);
 return <main className="label-screen">{controls&&<div className="label-controls"><button onClick={()=>window.print()}>Imprimir etiqueta</button><p>Papel 100 × 150 mm · Escala 100 % · Sin encabezados ni pies del navegador.</p></div>}<article className="package-label"><Image src={logo} alt="A&L Trucking Logistics" priority unoptimized className="label-logo"/><p className="label-caption">RECEPCIÓN DE PAQUETE · {position}</p><h1>{receptionCode??code}</h1>{receptionCode&&receptionCode!==code&&<p className="label-caption">Código de pieza: {code}</p>}<svg ref={barcode} role="img" aria-label={`Código de barras ${code}`}/><dl><div><dt>Casillero</dt><dd>{lockerCode}</dd></div><div><dt>Peso</dt><dd>{weightLb} lb</dd></div><div><dt>Medidas · largo × ancho × alto</dt><dd>{dimensions.length} × {dimensions.width} × {dimensions.height} in</dd></div></dl>{recipient&&<p className="label-recipient">Recibe: {recipient.name}<br/>{recipient.phone}</p>}<footer>Conservar esta etiqueta durante todo el recorrido.</footer></article><style>{`
 .label-screen{min-height:100vh;padding:24px;background:#eee;color:#111}.label-controls{max-width:100mm;margin:0 auto 20px;font-size:13px}.label-controls button{padding:12px 20px;border-radius:12px;background:#10203b;color:#fff;font-weight:bold;margin-bottom:10px}.package-label{box-sizing:border-box;width:100mm;height:149mm;padding:5mm;display:flex;flex-direction:column;background:white;margin:auto;text-align:center;overflow-wrap:anywhere}.label-logo{width:48mm;height:auto;margin:0 auto 3mm;max-height:26mm;object-fit:contain;flex-shrink:0}.label-caption{font-size:11px;letter-spacing:2px}.package-label h1{font-size:24px;font-weight:800;margin-top:4mm}.package-label svg{width:86mm;height:24mm;min-height:24mm;margin:2mm auto;flex-shrink:0}.package-label dl{border-top:2px solid #111;text-align:left;display:grid;gap:2mm;padding-top:3mm}.package-label dt{font-size:11px;text-transform:uppercase}.package-label dd{font-size:17px;font-weight:700}.package-label footer{font-size:10px;border-top:1px solid #bbb;margin-top:auto;padding-top:2mm;flex-shrink:0}.label-recipient{font-size:12px;line-height:1.25;margin:3mm 0}.package-label h1{font-size:20px;margin-top:2mm}@page{size:100mm 150mm;margin:0}@media print{.label-screen{padding:0;min-height:0;background:white;break-after:auto;page-break-after:auto;break-inside:avoid}.label-screen~.label-screen{break-before:page;page-break-before:always}html,body{margin:0!important;padding:0!important;min-height:0!important;height:auto!important}.label-controls{display:none}.package-label{margin:0;break-inside:avoid}}
 `}</style></main>;
}
