"use client";
import {Minus,Plus,ChevronLeft,ChevronRight} from "lucide-react";
import {formatUsd} from "@/lib/utils/format";
import styles from "./reception-pos.module.css";

import type {ReceptionPiece,SharedPieceFields} from "@/lib/utils/reception-pieces";
export type {ReceptionPiece} from "@/lib/utils/reception-pieces";
export function PackageQuantity({value,onChange}:{value:number;onChange:(n:number)=>void}){
 return <div className="flex items-center gap-4"><div><label htmlFor="reception-quantity" className="block text-xs font-medium text-navy-600">Cantidad de paquetes</label><p className="mt-1 text-[11px] text-navy-400">De 1 a 50 piezas</p></div><div className={styles.quantity}><button type="button" aria-label="Quitar un paquete" disabled={value<=1} onClick={()=>onChange(value-1)}><Minus className="size-3.5"/></button><input id="reception-quantity" aria-label="Cantidad de paquetes" type="number" inputMode="numeric" min="1" max="50" step="1" required value={value} onChange={e=>onChange(Math.max(1,Math.min(50,Math.trunc(Number(e.target.value)||1))))}/><button type="button" aria-label="Agregar un paquete" disabled={value>=50} onClick={()=>onChange(value+1)}><Plus className="size-3.5"/></button></div></div>;
}
const columns=[['length','Largo','in'],['width','Ancho','in'],['height','Alto','in'],['weightLb','Peso','lb']] as const;
export function PackageMeasurements({pieces,prices,manual,shared,page:requestedPage,onPageChange:setPage,onChange}:{pieces:ReceptionPiece[];prices:number[];manual:boolean;shared?:SharedPieceFields;page:number;onPageChange:(page:number)=>void;onChange:(i:number,field:keyof ReceptionPiece,value:number)=>void}){
 const page=Math.min(requestedPage,Math.max(0,Math.ceil(pieces.length/5)-1));
 const rows=pieces.slice(page*5,page*5+5);
 return <div className="min-w-0 border-t border-stone-100 pt-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold text-navy-950">Resto de paquetes</h3><p className="mt-1 text-xs text-navy-500">Una fila por pieza. El paquete 1 usa las medidas de arriba.</p></div><span className="text-xs tabular-nums text-navy-500">{pieces.length} piezas adicionales</span></div>
 <div className="overflow-x-auto"><table className={styles.pieces}><thead><tr><th scope="col">Pieza</th>{columns.map(([key,label,unit])=><th key={key} scope="col">{label} <span>({unit})</span></th>)}{manual&&<th scope="col">Precio <span>(USD)</span></th>}<th scope="col" className="text-right">Importe</th></tr></thead><tbody>{rows.map((p,row)=>{const i=page*5+row;return <tr key={i}><th scope="row"><span className="text-navy-400">#</span>{i+2}</th>{([...columns.map(c=>c[0]),...(manual?['customPriceUsd' as const]:[])]).map(field=><td key={field}><input aria-label={"Paquete "+(i+2)+" · "+({length:'Largo (in)',width:'Ancho (in)',height:'Alto (in)',weightLb:'Peso (lb)',customPriceUsd:'Precio (USD)'}[field])} readOnly={field==="weightLb"?shared?.weight:field==="customPriceUsd"?shared?.price:shared?.dimensions} title={(field==="weightLb"?shared?.weight:field==="customPriceUsd"?shared?.price:shared?.dimensions)?"Valor confirmado igual al paquete 1":undefined} type="number" inputMode="decimal" min="0.01" step="0.01" required placeholder="—" value={p[field]||''} onChange={e=>onChange(i,field,Number(e.target.value))}/></td>)}<td className="text-right font-semibold tabular-nums">{prices[i]>0?formatUsd(prices[i]):'—'}</td></tr>;})}</tbody></table></div>
 {pieces.length>5&&<nav aria-label="Páginas de paquetes" className="mt-3 flex items-center justify-between"><span className="text-xs text-navy-500">Piezas {page*5+2}–{Math.min(page*5+6,pieces.length+1)} de {pieces.length+1}</span><div className="flex items-center gap-2"><button type="button" aria-label="Paquetes anteriores" disabled={page===0} onClick={()=>setPage(page-1)} className="grid size-9 place-items-center rounded-lg border border-stone-200 disabled:opacity-30"><ChevronLeft className="size-4"/></button><button type="button" aria-label="Paquetes siguientes" disabled={(page+1)*5>=pieces.length} onClick={()=>setPage(page+1)} className="grid size-9 place-items-center rounded-lg border border-stone-200 disabled:opacity-30"><ChevronRight className="size-4"/></button></div></nav>}
 </div>;
}
