"use client";
import {useEffect,useState} from "react";
import {cloverAvailability} from "@/lib/auth/clover-actions";
import { Banknote, CreditCard, MapPin, ScrollText } from "lucide-react";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { formatUsd } from "@/lib/utils/format";
export type PaymentChoice = { method: "mixto" | "zelle" | "clover" | "efectivo" | "destino" | "tarjeta" | "transferencia" | "deposito" | "cheque"; parts?:Array<{method:"efectivo"|"zelle"|"transferencia"|"deposito"|"tarjeta"|"cheque";amount:string;reference:string}>; warehouseId?:string; amount: string; reference: string };
export function PaymentCapture({value,onChange,total,allowDestination=true,allowSplit=false,locations=[]}:{value:PaymentChoice;onChange:(value:PaymentChoice)=>void;total:number;allowDestination?:boolean;allowSplit?:boolean;locations?:{id:string;name:string}[]}){
 const [clover,setClover]=useState<{loading:boolean;enabled:boolean;issues:string[]}>({loading:true,enabled:false,issues:[]});
 const [check,setCheck]=useState(0);
 useEffect(()=>{
  let active=true;
  const timer=setTimeout(()=>{if(active){active=false;setClover({loading:false,enabled:false,issues:["La verificación tardó demasiado. Comprueba la conexión y vuelve a verificar."]});}},10000);
  cloverAvailability().then(result=>{if(active)setClover({loading:false,enabled:result.enabled,issues:result.issues??[]});}).catch(()=>{if(active)setClover({loading:false,enabled:false,issues:["No se pudo consultar Clover en el servidor. Revisa la conexión o recarga la página después del despliegue."]});}).finally(()=>clearTimeout(timer));
  return()=>{active=false;clearTimeout(timer);};
 },[check]);
 const options=[{value:"efectivo" as const,label:"Efectivo",icon:Banknote},...(allowDestination?[{value:"destino" as const,label:"En destino",icon:MapPin}]:[]),{value:"tarjeta" as const,label:"Tarjeta externa",icon:CreditCard},{value:"clover" as const,label:"Clover · cobrar",icon:CreditCard},{value:"transferencia" as const,label:"Transferencia",icon:Banknote},{value:"deposito" as const,label:"Depósito",icon:Banknote},{value:"zelle" as const,label:"Zelle",icon:Banknote},{value:"cheque" as const,label:"Cheque",icon:ScrollText},...(allowSplit?[{value:"mixto" as const,label:"Combinar pagos",icon:Banknote}]:[])];
 return <fieldset className="grid min-w-0 gap-3">
  <legend className="mb-2 text-sm font-semibold text-ink-700">Selecciona la forma de pago</legend>
  <div className={`grid gap-2 ${"grid-cols-2 sm:grid-cols-3"}`}>{options.map(option=><label key={option.value} className={`relative flex cursor-pointer flex-col items-center gap-2 rounded-xl border p-3 text-center text-sm font-semibold transition focus-within:ring-2 focus-within:ring-orange-500 ${option.value==="clover"&&!clover.enabled?"cursor-not-allowed border-stone-200 bg-stone-50 text-navy-400":value.method===option.value?"border-orange-500 bg-orange-50 text-orange-800":"border-stone-200 bg-white text-navy-600 hover:border-navy-400"}`}><input className="sr-only" type="radio" name="collectionMethod" value={option.value} disabled={option.value==="clover"&&!clover.enabled} aria-describedby={option.value==="clover"&&!clover.enabled?"clover-availability":undefined} checked={value.method===option.value} onChange={()=>onChange({...value,method:option.value,amount:"",reference:"",parts:option.value==="mixto"?(value.parts??[{method:"efectivo",amount:"",reference:""},{method:"zelle",amount:"",reference:""}]):undefined})}/><option.icon className="size-5" aria-hidden="true"/>{option.label}{option.value==="clover"&&!clover.enabled&&<span className="text-[10px] font-medium">{clover.loading?"Verificando…":"Requiere configuración"}</span>}</label>)}</div>
  {!clover.enabled&&<div id="clover-availability" role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950">{clover.loading?<p>Verificando configuración de Clover…</p>:<><p className="font-semibold">Clover está disponible como método, pero todavía no puede cobrar.</p><ul className="mt-2 list-disc space-y-1 pl-4">{(clover.issues.length?clover.issues:["El servidor no confirmó la configuración de Clover."]).map(issue=><li key={issue}>{issue}</li>)}</ul><p className="mt-2">Si ya actualizaste las variables, reinicia el proceso de la aplicación en PM2 para que las lea.</p><button type="button" className="mt-3 min-h-9 rounded-lg border border-amber-300 bg-white px-3 font-semibold hover:bg-amber-100" onClick={()=>{setClover({loading:true,enabled:false,issues:[]});setCheck(n=>n+1);}}>Volver a verificar</button></>}</div>}
  <div className="flex items-center justify-between gap-3 border-y border-stone-200 py-3"><span className="text-sm text-navy-500">Total a cubrir</span><strong className="font-display text-2xl text-navy-950">{total>0?formatUsd(total):"Por calcular"}</strong></div>
  {["tarjeta","transferencia","deposito","zelle","cheque"].includes(value.method)&&<Input name="cardAmount" label="Monto pagado (USD)" required type="number" min="0.01" step="0.01" inputMode="decimal" value={value.amount} onChange={e=>onChange({...value,amount:e.target.value})} hint="Importe recibido; debe coincidir con el total. No se realiza un cargo bancario desde aquí."/>}
  {value.method==="mixto"&&<div className="grid gap-3 rounded-xl border border-stone-200 p-3"><p className="text-xs text-navy-500">Registra importes ya recibidos. No realiza cargos bancarios. La suma debe cubrir el total.</p>{(value.parts??[]).map((part,index)=><div key={index} className="grid gap-2 border-b border-stone-100 pb-3"><div className="grid grid-cols-2 gap-2"><Select label={`Pago ${index+1} · método`} value={part.method} onChange={e=>onChange({...value,parts:value.parts!.map((p,i)=>i===index?{...p,method:e.target.value as typeof part.method}:p)})} options={[{value:"efectivo",label:"Efectivo"},{value:"zelle",label:"Zelle"},{value:"transferencia",label:"Transferencia"},{value:"deposito",label:"Depósito"},{value:"tarjeta",label:"Tarjeta externa"},{value:"cheque",label:"Cheque"}]}/><Input name={`splitAmount${index}`} label={`Pago ${index+1} · monto USD`} required type="number" min="0.01" step="0.01" value={part.amount} onChange={e=>onChange({...value,parts:value.parts!.map((p,i)=>i===index?{...p,amount:e.target.value}:p)})}/></div>{part.method!=="efectivo"&&<Input label={`Pago ${index+1} · ${part.method==="cheque"?"número de cheque":"referencia"} (opcional)`} value={part.reference} maxLength={160} onChange={e=>onChange({...value,parts:value.parts!.map((p,i)=>i===index?{...p,reference:e.target.value}:p)})}/>}<div className="flex justify-between gap-2"><button type="button" className="text-xs font-semibold text-brand-700" onClick={()=>onChange({...value,parts:value.parts!.map((p,i)=>i===index?{...p,amount:Math.max(0,total-value.parts!.reduce((s,q,j)=>j===index?s:s+(Number(q.amount)||0),0)).toFixed(2)}:p)})}>Completar restante</button>{value.parts!.length>2&&<button type="button" className="text-xs text-red-700" onClick={()=>onChange({...value,parts:value.parts!.filter((_,i)=>i!==index)})}>Quitar pago</button>}</div></div>)}{(value.parts?.length??0)<5&&<button type="button" className="text-sm font-semibold" onClick={()=>onChange({...value,parts:[...(value.parts??[]),{method:"transferencia",amount:"",reference:""}]})}>Agregar otro pago</button>}<p aria-live="polite" className="text-sm font-semibold">Diferencia: {formatUsd(total-(value.parts??[]).reduce((s,p)=>s+(Number(p.amount)||0),0))}</p></div>}
  <Select label="Ubicación del registro" required value={value.warehouseId??(locations.length===1?locations[0].id:"")} onChange={e=>onChange({...value,warehouseId:e.target.value})} options={[{value:"",label:"Selecciona almacén"},...locations.map(w=>({value:w.id,label:w.name}))]}/>
  {["tarjeta","transferencia","deposito","zelle","cheque"].includes(value.method)&&<Input name="paymentReference" label={value.method==="cheque"?"Número de cheque / referencia (opcional)":"Referencia externa / transacción (opcional)"} maxLength={160} placeholder={value.method==="cheque"?"Ej. CH-001234":"Ej. autorización o referencia bancaria"} value={value.reference} onChange={e=>onChange({...value,reference:e.target.value})} hint={value.method==="cheque"?"Registra el número del cheque si lo tienes. El folio interno se genera automáticamente.":"No incluyas datos completos de tarjeta. El folio interno se genera automáticamente."}/>}
  <p className={`rounded-xl p-3 text-sm leading-5 ${value.method==="destino"?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-900"}`}>{value.method==="clover"?"Completa la tarjeta en el formulario seguro. Solo se confirmará el pago cuando Clover lo apruebe.":value.method==="destino"?"Pendiente de pago en destino. Se generará un folio de acuerdo; no registra dinero recibido.":"Al guardar confirmas que recibiste el total. Se generará un folio de pago único y quedará registrado en la factura."}</p>
 </fieldset>;
}
