"use client";
import {useEffect,useState} from "react";
import {getReceptionContacts} from "@/lib/auth/reception-contacts";
import {upsertCustomerRecipient,deleteCustomerRecipient} from "@/lib/auth/admin-actions";
import {Dialog} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {Button} from "@/components/ui/button";
import Link from "next/link";
export function ReceptionRecipient({userId,value,onChange}:{userId:string;value:string;onChange:(id:string)=>void}){
 const [data,setData]=useState<Awaited<ReturnType<typeof getReceptionContacts>>>({recipients:[],addresses:[]}),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [person,setPerson]=useState({id:"",name:"",phone:"",addressId:""});
 useEffect(()=>{let alive=true;getReceptionContacts(userId).then(d=>{if(alive){setData(d);setLoading(false);}}).catch(()=>{if(alive){setMessage("No se pudieron cargar los destinatarios. Vuelve a seleccionar al cliente.");setLoading(false);}});return()=>{alive=false;};},[userId]);
 const selected=data.recipients.find(r=>r.id===value);
 const found=data.recipients.filter(r=>[r.name,r.phone].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <div className="grid gap-3 rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">Quién recibe en México</strong><Button type="button" variant="ghost" disabled={loading} onClick={()=>{setPerson({id:"",name:"",phone:"",addressId:data.addresses[0]?.id??""});setOpen(true);}}>Agregar destinatario</Button></div>{loading?<p role="status">Cargando destinatarios…</p>:<><Input label="Buscar destinatario por nombre o teléfono" value={query} onChange={e=>setQuery(e.target.value)}/><Select label="Destinatario de estos paquetes" required value={value} options={[{value:"",label:"Selecciona quién recibe"},...(selected&&!found.some(r=>r.id===selected.id)?[selected,...found.slice(0,30)]:found.slice(0,30)).map(r=>({value:r.id,label:`${r.name} · ${r.phone}`}))]} onChange={e=>onChange(e.target.value)}/>{found.length>30&&<p className="text-xs">Refina la búsqueda para ver los demás destinatarios.</p>}{selected&&<div className="flex flex-wrap gap-3"><Button type="button" variant="ghost" onClick={()=>{setPerson(selected);setOpen(true);}}>Editar destinatario</Button><Button type="button" variant="ghost" onClick={()=>onChange("")}>Quitar selección</Button><Button type="button" variant="ghost" disabled={busy} onClick={async()=>{if(!window.confirm("¿Eliminar este destinatario del cliente? Si tiene paquetes o envíos vinculados se conservará."))return;setBusy(true);try{const r=await deleteCustomerRecipient(userId,selected.id);if(!r.ok){setMessage(r.error);return;}setData(d=>({...d,recipients:d.recipients.filter(p=>p.id!==selected.id)}));onChange("");}catch{setMessage("No se confirmó la eliminación.");}finally{setBusy(false);}}}>Eliminar del cliente</Button></div>}</>}<p role="status" className="text-sm text-orange-700">{message}</p>
 <Dialog open={open} onClose={()=>{if(!busy)setOpen(false);}} title={person.id?"Editar destinatario":"Agregar destinatario"}><form className="grid gap-4" onSubmit={async e=>{e.preventDefault();e.stopPropagation();setBusy(true);try{const r=await upsertCustomerRecipient(userId,person,person.id||undefined);if(!r.ok){setMessage(r.error);return;}setData(d=>({...d,recipients:[...d.recipients.filter(p=>p.id!==r.recipient.id),r.recipient]}));onChange(r.recipient.id);setQuery("");setOpen(false);setMessage("");}catch{setMessage("No se pudo guardar el destinatario.");}finally{setBusy(false);}}}><Input label="Nombre completo de quien recibe" required value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/><Input label="Teléfono de quien recibe" type="tel" required value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/><Select label="Dirección en México" required value={person.addressId} options={[{value:"",label:"Selecciona dirección"},...data.addresses.map(a=>({value:a.id,label:`${a.label} · ${a.street} ${a.exteriorNumber}, ${a.municipality}`}))]} onChange={e=>setPerson({...person,addressId:e.target.value})}/><Link href={`/admin/clientes/${userId}`} target="_blank" className="text-sm underline">Gestionar direcciones del cliente</Link><Button type="button" variant="ghost" onClick={async()=>setData(await getReceptionContacts(userId))}>Actualizar direcciones</Button><p role="status" className="text-sm text-orange-700">{message}</p><Button type="submit" loading={busy}>Guardar destinatario</Button></form></Dialog>
 </div>;
}
