import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {afterEach,expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {ReceptionRecipient} from './reception-recipient';
import {ReceptionForm} from './reception-form';
import {BOX_CATEGORIES} from '@/lib/config/box-categories';
import {getReceptionContacts} from '@/lib/auth/reception-contacts';
import {upsertCustomerRecipient} from '@/lib/auth/admin-actions';
import {receivePackageGroup,completeReceptionPayment} from '@/lib/auth/file-actions';
import {cloverAvailability,submitCloverPayment} from '@/lib/auth/clover-actions';
const {tokenize}=vi.hoisted(()=>({tokenize:vi.fn(async()=> 'clv_test')}));
vi.mock('@/components/payments/clover-card-fields',()=>({CloverCardFields:({ref,onReady}:{ref:React.Ref<unknown>;onReady:(ready:boolean)=>void})=>{React.useImperativeHandle(ref,()=>({tokenize}));React.useEffect(()=>{onReady(true);return()=>onReady(false);},[onReady]);return <div>Campos seguros Clover</div>;}}));
vi.mock('@/lib/auth/reception-contacts',()=>({getReceptionContacts:vi.fn()}));
vi.mock('@/lib/auth/admin-actions',()=>({upsertCustomerRecipient:vi.fn(),deleteCustomerRecipient:vi.fn()}));
vi.mock('@/lib/auth/file-actions',()=>({receivePackageGroup:vi.fn(),completeReceptionPayment:vi.fn()}));
vi.mock('@/lib/auth/clover-actions',()=>({cloverAvailability:vi.fn(async()=>({enabled:false})),prepareCloverPayment:vi.fn(),submitCloverPayment:vi.fn(),reconcileCloverPayment:vi.fn()}));
vi.mock('@/lib/auth/warehouse-actions',()=>({selectPrealertAtWarehouse:vi.fn()}));
vi.mock('@/components/ui/toast',()=>({useToast:()=>({showToast:vi.fn()})}));
vi.mock('./customer-quick-create',()=>({CustomerQuickCreate:()=>null}));
vi.mock('./customer-search',()=>({CustomerSearch:({onChange}:{onChange:(id:string)=>void})=><div>{['one','two','three'].map(id=><button key={id} type="button" data-client={id} onClick={()=>onChange(id)}>{id}</button>)}</div>}));
vi.stubGlobal('React',React);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);
const mounts:Array<{root:ReturnType<typeof createRoot>;node:HTMLElement}>=[];
function mount(element:React.ReactNode){const node=document.createElement('div');document.body.append(node);const root=createRoot(node);mounts.push({root,node});act(()=>root.render(element));return {root,node};}
afterEach(()=>{for(const {root,node} of mounts.splice(0)){act(()=>root.unmount());node.remove();}vi.clearAllMocks();vi.mocked(cloverAvailability).mockResolvedValue({enabled:false,issues:[]});});
const addr={id:'a',userId:'u',label:'Casa',street:'Reforma',exteriorNumber:'10',neighborhood:'Centro',postalCode:'49540',municipality:'Valle de Juárez',state:'Jalisco'};
const person={id:'r',userId:'u',name:'Juan Perez',phone:'5512345678',addressId:'a'};
it('captures a motorcycle and jointly weighed boxes as separate concepts in one reception',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:false,error:'Captured'});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[...BOX_CATEGORIES]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 const click=async(text:string)=>act(async()=>Array.from(node.querySelectorAll<HTMLButtonElement>('button')).find(b=>b.textContent?.includes(text))!.click());
 const field=(article:Element,label:string)=>{const l=Array.from(article.querySelectorAll<HTMLLabelElement>('label')).find(l=>l.textContent===label)!;return document.getElementById(l.htmlFor) as HTMLInputElement;};
 const change=async(element:HTMLInputElement|HTMLSelectElement,value:string)=>act(async()=>{Object.getOwnPropertyDescriptor(element instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(element,value);element.dispatchEvent(new Event(element instanceof HTMLSelectElement?'change':'input',{bubbles:true}));});
 await click('Varios conceptos');
 let articles=node.querySelectorAll('[aria-label="Conceptos de la recepción"] article');
 await change(field(articles[0],'Contenido del concepto 1'),'Moto Honda · VIN 201285');
 await change(field(articles[0],'Precio total de este concepto (USD)'),'3000');
 await act(async()=>articles[0].querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());
 await click('Añadir otro concepto');articles=node.querySelectorAll('[aria-label="Conceptos de la recepción"] article');
 await change(field(articles[1],'Contenido del concepto 2'),'Cajas de ropa');
 await change(field(articles[1],'Piezas'),'5');
 await change(articles[1].querySelector<HTMLSelectElement>('select')!,'peso-personalizado');
 await change(field(articles[1],'Peso conjunto de este concepto (lb)'),'117');
 await change(field(articles[1],'Tarifa por libra (USD)'),'3.20');
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$3,374.40');
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('6 piezas · 2 conceptos');
 expect(node.querySelector<HTMLButtonElement>('button[type="submit"]')!.disabled).toBe(false);
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(receivePackageGroup).toHaveBeenCalledTimes(1);
 const args=vi.mocked(receivePackageGroup).mock.calls[0];expect(args[0]).toHaveLength(1);expect(args[4]).toBeUndefined();
 expect(args[5]).toMatchObject([{description:'Moto Honda · VIN 201285',quantity:1,mode:'manual',weightUnknown:true,priceUsd:3000},{description:'Cajas de ropa',quantity:5,mode:'peso-personalizado',weightScope:'grupo',weightLb:117,rateUsd:3.2}]);
});
it('charges fixed catalog prices for multiple boxes and clears the selection when switching to volume',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:false,error:'Captured'});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[...BOX_CATEGORIES]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;
 await act(async()=>{select.value='fijo';select.dispatchEvent(new Event('change',{bubbles:true}));});
 const cards=node.querySelector('[aria-label="Precios fijos por caja"]')!;
 expect(cards.textContent).toContain('$80.00');
 expect(cards.textContent).toContain('$110.00');
 expect(cards.textContent).not.toContain('$36.48');
 await act(async()=>cards.querySelector<HTMLButtonElement>('[aria-label="Añadir caja Small"]')!.click());
 await fill('weightLb','40');
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$80.00');
 await act(async()=>node.querySelector<HTMLButtonElement>('[aria-label="Añadir caja Small"]')!.click());
 const weight=node.querySelector<HTMLInputElement>('[aria-label="Paquete 2 · Peso (lb)"]')!;
 await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(weight,'45');weight.dispatchEvent(new Event('input',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$160.00');
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 const batch=vi.mocked(receivePackageGroup).mock.calls[0][0] as Array<Record<string,unknown>>;
 expect(batch).toHaveLength(2);
 expect(batch[0]).toMatchObject({billingMode:'fijo',overrideCategory:'small',length:10,width:16,height:12,weightLb:40});
 expect(batch[1]).toMatchObject({billingMode:'fijo',overrideCategory:'small',length:10,width:16,height:12,weightLb:45});
 await act(async()=>{select.value='volumen';select.dispatchEvent(new Event('change',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Precios fijos por caja"]')).toBeNull();
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$72.96');
});
it('combines two Small, one Medium and one Large with independent weights and a live fixed total',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:false,error:'Captured'});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[...BOX_CATEGORIES]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await act(async()=>{const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;select.value='fijo';select.dispatchEvent(new Event('change',{bubbles:true}));});
 for(const size of ['Small','Small','Medium','Large'])await act(async()=>node.querySelector<HTMLButtonElement>(`[aria-label="Añadir caja ${size}"]`)!.click());
 expect(node.querySelector('[aria-label="Composición de cajas"]')?.textContent).toContain('2 × Small');
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$450.00');
 expect(node.querySelector<HTMLButtonElement>('button[type="submit"]')?.disabled).toBe(true);
 expect(Array.from(node.querySelectorAll<HTMLInputElement>('input[name^="catalogWeight"]')).every(input=>input.value==='')).toBe(true);
 for(const [index,weight] of [20,25,40,60].entries())await fill(index===0?'weightLb':`catalogWeight${index+1}`,String(weight));
 const third=node.querySelector<HTMLSelectElement>('[aria-label="Paquete 3 · Caja del catálogo"]')!;
 await act(async()=>{third.value='large';third.dispatchEvent(new Event('change',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$520.00');
 expect(node.querySelector<HTMLInputElement>('[name="catalogWeight3"]')?.value).toBe('40');
 await act(async()=>{third.value='medium';third.dispatchEvent(new Event('change',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('4 de 4 cajas con peso validado');
 expect(node.querySelector<HTMLButtonElement>('button[type="submit"]')?.disabled).toBe(false);
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 const batch=vi.mocked(receivePackageGroup).mock.calls[0][0] as Array<Record<string,unknown>>;
 expect(batch).toHaveLength(4);
 expect(batch.map(item=>item.overrideCategory)).toEqual(['small','small','medium','large']);
 expect(batch.map(item=>item.weightLb)).toEqual([20,25,40,60]);
 expect(batch.map(item=>[item.length,item.width,item.height])).toEqual([[10,16,12],[10,16,12],[16,20,15],[16,26,15]]);
 expect(batch.every(item=>item.billingMode==='fijo')).toBe(true);
 // Switching away and back must preserve the mixed catalog without stale form values.
 const method=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;
 await act(async()=>{method.value='volumen';method.dispatchEvent(new Event('change',{bubbles:true}));});
 await act(async()=>{method.value='fijo';method.dispatchEvent(new Event('change',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('$450.00');
 expect(node.querySelector<HTMLButtonElement>('button[type="submit"]')?.disabled).toBe(false);
 vi.mocked(receivePackageGroup).mockClear();
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(receivePackageGroup).toHaveBeenCalledTimes(1);
});
it('does not silently upgrade a selected fixed box when it exceeds the catalog limit',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[...BOX_CATEGORIES]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await act(async()=>{const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;select.value='fijo';select.dispatchEvent(new Event('change',{bubbles:true}));});
 await act(async()=>node.querySelector<HTMLButtonElement>('[aria-label="Añadir caja Small"]')!.click());
 await fill('weightLb','55');
 expect(node.textContent).toContain('la caja elegida no admite este peso');
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('0 de 1');
 expect(node.querySelector<HTMLButtonElement>('button[type="submit"]')?.disabled).toBe(true);
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(receivePackageGroup).not.toHaveBeenCalled();
});
it('captures one group weight and a variable rate with cash and Zelle without thirteen weight inputs',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:false,error:'Test captured, no save'});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} locations={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await act(async()=>{const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;select.value='peso-personalizado';select.dispatchEvent(new Event('change',{bubbles:true}));});
 await act(async()=>{const input=node.querySelector<HTMLInputElement>('[aria-label="Cantidad de paquetes"]')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,'13');input.dispatchEvent(new Event('input',{bubbles:true}));});
 await act(async()=>{const label=Array.from(node.querySelectorAll('label')).find(l=>l.textContent==='Cómo se pesaron los paquetes')!;const select=document.getElementById(label.htmlFor) as HTMLSelectElement;select.value='grupo';select.dispatchEvent(new Event('change',{bubbles:true}));});
 await fill('weightLb','726');await fill('customRatePerLbUsd','3.50');
 await act(async()=>{const note=node.querySelector<HTMLTextAreaElement>('[name="contentsNote"]')!;Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!.call(note,'13 cajas de ropa y artículos personales');note.dispatchEvent(new Event('input',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Paquete 2 · Peso (lb)"]')).toBeNull();
 expect(node.querySelector('[aria-label="Total de recepción"]')?.textContent).toContain('2,541.00');
 await act(async()=>node.querySelector<HTMLInputElement>('input[value="mixto"]')!.click());
 const first=node.querySelector<HTMLInputElement>('[name="splitAmount0"]')!;
 await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(first,'1000');first.dispatchEvent(new Event('input',{bubbles:true}));});
 await act(async()=>Array.from(node.querySelectorAll('button')).filter(b=>b.textContent==='Completar restante')[1].click());
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 const args=vi.mocked(receivePackageGroup).mock.calls[0];expect(args[0]).toHaveLength(13);expect((args[0] as Array<{contentsNote?:string}>).every(item=>item.contentsNote==='13 cajas de ropa y artículos personales')).toBe(true);expect(args[4]).toEqual({totalWeightLb:726});expect(args[2]).toMatchObject({method:'mixto',parts:[{method:'efectivo',amount:'1000'},{method:'zelle',amount:'1541.00'}]});
});
it('submits a cheque with its amount and optional number from reception',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:false,error:'Captured'});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} locations={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await fill('weightLb','10');
 await act(async()=>node.querySelector<HTMLInputElement>('input[value="cheque"]')!.click());
 await fill('cardAmount','32');await fill('paymentReference','CH-0042');
 expect(node.textContent).toContain('Número de cheque / referencia (opcional)');
 expect(node.querySelector<HTMLInputElement>('[name="paymentReference"]')?.required).toBe(false);
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(vi.mocked(receivePackageGroup).mock.calls[0][2]).toMatchObject({method:'cheque',amount:'32',reference:'CH-0042',warehouseId:'origin'});
});
it('shows secure fields before saving and changes a declined card to cash without creating more packages',async()=>{
 vi.mocked(cloverAvailability).mockResolvedValue({enabled:true,environment:'sandbox',issues:[]});
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:true,results:[{box:{id:'b1',status:'en-bodega'},invoice:{id:'i1'}}],total:32} as never);
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} locations={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await fill('weightLb','10');await act(async()=>node.querySelector<HTMLInputElement>('input[value="clover"]')!.click());
 expect(node.textContent).toContain('Campos seguros Clover');expect(receivePackageGroup).not.toHaveBeenCalled();
 vi.mocked(submitCloverPayment).mockResolvedValue({ok:true,attempt:{status:'declined'}} as never);
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(tokenize).toHaveBeenCalledTimes(1);expect(receivePackageGroup).toHaveBeenCalledTimes(1);const [items,,payment,request]=vi.mocked(receivePackageGroup).mock.calls[0];expect(payment).toBeUndefined();expect((items as {invoiceNow:boolean}[])[0].invoiceNow).toBe(true);
 expect(node.querySelector('form')).not.toBeNull();expect(node.textContent).toContain('Tarjeta rechazada');
 vi.mocked(completeReceptionPayment).mockResolvedValue({ok:true,results:[{box:{id:'b1',status:'en-bodega'},invoice:{id:'i1'}}],total:32} as never);
 await act(async()=>node.querySelector<HTMLInputElement>('input[value="efectivo"]')!.click());
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(completeReceptionPayment).toHaveBeenCalledWith(request,expect.objectContaining({method:'efectivo'}));expect(receivePackageGroup).toHaveBeenCalledTimes(1);expect(node.textContent).toContain('paquete registrado');
});
it('does not save a reception when secure card tokenization fails',async()=>{
 vi.mocked(cloverAvailability).mockResolvedValue({enabled:true,environment:'sandbox',issues:[]});
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 tokenize.mockRejectedValueOnce(new Error('Revisa la tarjeta'));
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} locations={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await fill('weightLb','10');await act(async()=>node.querySelector<HTMLInputElement>('input[value="clover"]')!.click());
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(receivePackageGroup).not.toHaveBeenCalled();expect(submitCloverPayment).not.toHaveBeenCalled();expect(node.textContent).toContain('Revisa la tarjeta');
});
it('submits real weights without dimensions and starts a clean next reception without refresh',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 vi.mocked(receivePackageGroup).mockResolvedValue({ok:true,results:[{box:{id:'b1',status:'en-bodega'}},{box:{id:'b2',status:'en-bodega'}}],total:761.6} as never);
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 expect(node.querySelector('[name="length"]')).toBeNull();
 await fill('weightLb','55');
 act(()=>node.querySelector<HTMLButtonElement>('[aria-label="Agregar un paquete"]')!.click());
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('Subtotal provisional');
 expect(Array.from(node.querySelectorAll('input[type="checkbox"]')).find(e=>e.closest("label")?.textContent?.includes('Confirmo el mismo peso'))).toHaveProperty('checked',false);
 await act(async()=>{const el=node.querySelector<HTMLInputElement>('[aria-label="Paquete 2 · Peso (lb)"]')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,'140');el.dispatchEvent(new Event('input',{bubbles:true}));});
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('2 de 2 unidades calculadas');
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('624.00');
 expect(receivePackageGroup).not.toHaveBeenCalled();
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 const batch=vi.mocked(receivePackageGroup).mock.calls[0][0] as Array<{length:number;weightLb:number}>;
 expect(batch.map(p=>p.weightLb)).toEqual([55,140]);expect(batch.map(p=>p.length)).toEqual([0,0]);
 expect(node.textContent).toContain('2 paquetes registrados');expect(node.querySelector('form')).toBeNull();
 await act(async()=>Array.from(node.querySelectorAll('button')).find(b=>b.textContent?.includes('Registrar otro paquete'))!.click());
 expect(node.querySelector('[name="length"]')).toBeNull();expect(node.querySelector<HTMLInputElement>('[name="weightLb"]')!.value).toBe('');expect(node.querySelector<HTMLInputElement>('[aria-label="Cantidad de paquetes"]')!.value).toBe('1');expect(node.textContent).toContain('Juan Perez');
});
it('quotes volume before weighing and keeps the same total when actual weight increases',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person],addresses:[addr]});
 const {node}=mount(<ReceptionForm users={[]} defaultCustomerId="u" rates={[]} origins={[{id:'origin',name:'Origen'}]} excessPolicy="recargo"/>);await act(async()=>{});
 await act(async()=>{const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;select.value='volumen';select.dispatchEvent(new Event('change',{bubbles:true}));});
 await fill('length','16');await fill('width','26');await fill('height','15');
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('118.56');
 await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(receivePackageGroup).not.toHaveBeenCalled();
 await fill('weightLb','500');
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('118.56');
 await act(async()=>{const select=node.querySelector<HTMLSelectElement>('[name="billingMode"]')!;select.value='peso-real';select.dispatchEvent(new Event('change',{bubbles:true}));});
 expect(node.querySelector('[name="length"]')).toBeNull();
 expect(node.querySelector('[aria-label="Total de recepción"]')!.textContent).toContain('1,600.00');
});
it('defaults to the initial recipient, hides search, and lets the operator switch without overwriting the choice',async()=>{
 const second={...person,id:'second',name:'María López'};
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[person,second],addresses:[addr]});
 function Harness(){const [value,setValue]=useState('');return <ReceptionRecipient userId="u" value={value} onChange={setValue}/>;}
 const {node}=mount(<Harness/>);await act(async()=>{});
 expect(node.textContent).toContain('Juan Perez');expect(node.textContent).toContain('Principal');expect(node.textContent).toContain('Reforma 10');expect(node.querySelector('input')).toBeNull();
 act(()=>Array.from(node.querySelectorAll('button')).find(b=>b.textContent==='Cambiar destinatario')!.click());
 const dialog=document.querySelector('[role="dialog"]')!;
 act(()=>Array.from(dialog.querySelectorAll('button')).find(b=>b.textContent?.includes('María López'))!.click());
 expect(node.textContent).toContain('María López');expect(node.textContent).not.toContain('Juan Perez');expect(document.querySelector('[role="dialog"]')).toBeNull();
});
async function fill(name:string,value:string){await act(async()=>{const el=document.querySelector<HTMLInputElement>('[name="'+name+'"]')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});}
it('uses distinct sibling keys for recipients and prealerts',()=>{const source=readFileSync('src/components/admin/reception-form.tsx','utf8');expect(source).toContain('key={`recipient:${values.customer}`}');expect(source).toContain('key={`prealert:${values.customer??""}`}');});
it('keeps exactly one recipient block in the actual reception form through repeated client changes',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[],addresses:[]});
 const errors=vi.spyOn(console,'error');
 try{
  const {node}=mount(<ReceptionForm users={[]} rates={[]} excessPolicy="recargo"/>);
  for(const id of ['one','two','three','one','two','three']){
   await act(async()=>node.querySelector<HTMLButtonElement>('[data-client="'+id+'"]')!.click());
   expect(node.querySelectorAll('[data-testid="reception-recipient"]')).toHaveLength(1);
   expect(node.textContent?.match(/Quién recibe en México/g)).toHaveLength(1);
  }
  expect(errors.mock.calls.flat().join(' ')).not.toContain('same key');
 }finally{errors.mockRestore();}
});
it('creates recipient and new address from an empty client without submitting reception',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[],addresses:[]});
 vi.mocked(upsertCustomerRecipient).mockResolvedValue({ok:true,user:{} as never,recipient:person,address:addr});
 const onChange=vi.fn(),outer=vi.fn(e=>e.preventDefault());
 const {node}=mount(<form onSubmit={outer}><ReceptionRecipient userId="u" value="" onChange={onChange}/></form>);
 await act(async()=>{});expect(node.textContent).toContain('todavía no tiene destinatarios');
 act(()=>node.querySelector('button')!.click());
 await fill('recipientName',person.name);await fill('recipientPhone',person.phone);
 await act(async()=>{const select=document.querySelector<HTMLSelectElement>('[role="dialog"] select')!;select.value='new';select.dispatchEvent(new Event('change',{bubbles:true}));});
 for(const key of ['label','street','exteriorNumber','neighborhood','postalCode','municipality','state'] as const)await fill('address-'+key,addr[key]);
 await act(async()=>{document.querySelector('[role="dialog"] form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
 expect(outer).not.toHaveBeenCalled();expect(upsertCustomerRecipient).toHaveBeenCalledWith('u',expect.objectContaining({name:person.name}),undefined,expect.objectContaining({street:'Reforma',postalCode:'49540'}));expect(onChange).toHaveBeenCalledWith('r');expect(node.textContent).toContain('guardado y seleccionado');expect(node.querySelectorAll('[data-testid="reception-recipient"]')).toHaveLength(1);
});
it('ignores stale requests after switching clients and allows retry after failure',async()=>{
 let resolve!:(v:{recipients:typeof person[];addresses:typeof addr[]})=>void;
 vi.mocked(getReceptionContacts).mockImplementationOnce(()=>new Promise(r=>{resolve=r;})).mockRejectedValueOnce(new Error('offline')).mockResolvedValue({recipients:[],addresses:[]});
 const {root,node}=mount(<ReceptionRecipient userId="old" value="" onChange={vi.fn()}/>);
 await act(async()=>root.render(<ReceptionRecipient userId="new" value="" onChange={vi.fn()}/>));
 await act(async()=>resolve({recipients:[person],addresses:[addr]}));
 expect(node.textContent).not.toContain(person.name);expect(node.textContent).toContain('No se pudieron');
 await act(async()=>Array.from(node.querySelectorAll('button')).find(b=>b.textContent==='Reintentar')!.click());
 expect(node.textContent).toContain('todavía no tiene');expect(node.querySelectorAll('[data-testid="reception-recipient"]')).toHaveLength(1);
});
it('selects a saved address and keeps server validation visible in the dialog',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[],addresses:[addr]});vi.mocked(upsertCustomerRecipient).mockResolvedValue({ok:false,error:'Revisa el teléfono.'});
 const {node}=mount(<ReceptionRecipient userId="u" value="" onChange={vi.fn()}/>);await act(async()=>{});act(()=>node.querySelector('button')!.click());
 expect(document.querySelector('[role="dialog"]')!.textContent).toContain('Dirección guardada');
 await act(async()=>document.querySelector('[role="dialog"] form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 expect(upsertCustomerRecipient).toHaveBeenCalledWith('u',expect.objectContaining({addressId:'a'}),undefined,undefined);
 expect(document.querySelector('[role="dialog"] [role="alert"]')!.textContent).toBe('Revisa el teléfono.');
});
it('does not select a recipient on the new client when an earlier save finishes late',async()=>{
 vi.mocked(getReceptionContacts).mockResolvedValue({recipients:[],addresses:[addr]});
 let resolve!:(v:Awaited<ReturnType<typeof upsertCustomerRecipient>>)=>void;
 vi.mocked(upsertCustomerRecipient).mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));
 const onChange=vi.fn(),{node,root}=mount(<ReceptionRecipient userId="u" value="" onChange={onChange}/>);
 await act(async()=>{});act(()=>node.querySelector('button')!.click());
 await act(async()=>{document.querySelector('[role="dialog"] form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
 await act(async()=>root.render(<ReceptionRecipient userId="other" value="" onChange={onChange}/>));
 await act(async()=>resolve({ok:true,user:{} as never,recipient:person,address:addr}));
 expect(onChange).not.toHaveBeenCalled();expect(document.querySelector('[role="dialog"]')).toBeNull();
});
