"use client";
import {useEffect,useRef,useState} from "react";
import {getReceptionContacts} from "@/lib/auth/reception-contacts";
import {upsertCustomerRecipient,deleteCustomerRecipient} from "@/lib/auth/admin-actions";
import {Dialog} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import { ArrowLeftRight, MapPin, Phone, Plus, Pencil, Check, Trash2 } from "lucide-react";
import {Button} from "@/components/ui/button";

const emptyAddress={label:"Principal",street:"",exteriorNumber:"",interiorNumber:"",neighborhood:"",postalCode:"",municipality:"",state:"",references:""};
const fields: Array<[keyof typeof emptyAddress,string,boolean]>=[["label","Nombre de la dirección",true],["street","Calle",true],["exteriorNumber","Número exterior",true],["interiorNumber","Número interior",false],["neighborhood","Colonia",true],["postalCode","Código postal",true],["municipality","Municipio / ciudad",true],["state","Estado",true],["references","Referencias",false]];
type Props={userId:string;value:string;onChange:(id:string)=>void};
export function ReceptionRecipient(props:Props){return <RecipientEditor key={props.userId} {...props}/>;}
function RecipientEditor({userId,value,onChange}:Props){
 const active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const initialValue=useRef(value),changeRef=useRef(onChange);
 useEffect(()=>{changeRef.current=onChange;},[onChange]);
 const [choosing,setChoosing]=useState(false);
 const [data,setData]=useState<Awaited<ReturnType<typeof getReceptionContacts>>>({recipients:[],addresses:[]});
 const [loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [person,setPerson]=useState({id:"",name:"",phone:"",addressId:""});
 const [newAddress,setNewAddress]=useState(false),[address,setAddress]=useState(emptyAddress);
 useEffect(()=>{let alive=true;getReceptionContacts(userId).then(d=>{if(alive){setData(d);setLoading(false);setFailed(false);if(!initialValue.current){const first=d.recipients.find(r=>d.addresses.some(a=>a.id===r.addressId));if(first){initialValue.current=first.id;changeRef.current(first.id);}}}}).catch(()=>{if(alive){setFailed(true);setLoading(false);}});return()=>{alive=false;};},[userId,retry]);
 const selected=data.recipients.find(r=>r.id===value);
 const selectedAddress=data.addresses.find(a=>a.id===selected?.addressId);
 const found=data.recipients.filter(r=>(r.name+" "+r.phone).toLowerCase().includes(query.toLowerCase()));
 const options=found.slice(0,30);
 function start(edit=false){setMessage("");setPerson(edit&&selected?selected:{id:"",name:"",phone:"",addressId:data.addresses[0]?.id??""});setAddress({...emptyAddress});setNewAddress(!data.addresses.length);setOpen(true);}
 return <div data-testid="reception-recipient" className="grid gap-3 border-t border-stone-100 pt-4">
 <div className="flex items-center justify-between gap-3"><strong className="text-xs font-medium text-navy-500">Quién recibe en México</strong>{!loading&&!failed&&<button type="button" onClick={()=>selected?setChoosing(true):start()} className="inline-flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-semibold text-navy-700 transition hover:bg-stone-100">{selected?<ArrowLeftRight className="size-3.5"/>:<Plus className="size-3.5"/>}{selected?"Cambiar destinatario":"Agregar destinatario"}</button>}</div>
 {loading?<p role="status" className="animate-pulse text-sm text-navy-400">Consultando contacto de entrega…</p>:failed?<div role="alert"><p>No se pudieron consultar los destinatarios.</p><Button type="button" onClick={()=>{setLoading(true);setRetry(n=>n+1);}}>Reintentar</Button></div>:selected?<div className="flex items-start gap-3"><span className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-full bg-orange-50 text-orange-700"><MapPin className="size-4"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-navy-950">{selected.name}</p>{selected.id===data.recipients[0]?.id&&<span className="rounded bg-stone-100 px-1.5 py-0.5 text-[10px] font-medium text-navy-500">Principal</span>}</div><p className="mt-1 flex items-center gap-1.5 text-xs text-navy-500"><Phone className="size-3"/>{selected.phone}</p><p className="mt-1.5 max-w-lg text-xs leading-5 text-navy-500">{selectedAddress?[selectedAddress.street+" "+selectedAddress.exteriorNumber,selectedAddress.interiorNumber,selectedAddress.neighborhood,selectedAddress.municipality,selectedAddress.state,"CP "+selectedAddress.postalCode].filter(Boolean).join(", "):"Sin dirección válida. Edita el destinatario."}</p></div><button type="button" aria-label="Editar destinatario" className="grid size-8 shrink-0 place-items-center rounded-lg text-navy-400 hover:bg-stone-100 hover:text-navy-900" onClick={()=>start(true)}><Pencil className="size-3.5"/></button></div>:<div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-navy-500">{data.recipients.length?"Elige quién recibirá estos paquetes.":"Este cliente todavía no tiene destinatarios."}</p>{data.recipients.length>0&&<button type="button" className="text-sm font-semibold text-brand-700" onClick={()=>setChoosing(true)}>Elegir destinatario</button>}</div>}
 <Dialog open={choosing} onClose={()=>setChoosing(false)} title="Elegir destinatario" description="Contactos de entrega de este cliente. El cambio aplica a esta recepción.">
 <div className="grid gap-4"><Input autoFocus label="Buscar destinatario por nombre o teléfono" value={query} onChange={e=>setQuery(e.target.value)}/><div className="grid max-h-[40vh] gap-1 overflow-y-auto">{options.map(r=>{const a=data.addresses.find(a=>a.id===r.addressId);return <button type="button" key={r.id} aria-pressed={r.id===value} onClick={()=>{onChange(r.id);setChoosing(false);setMessage("");}} className="flex items-start justify-between gap-3 rounded-xl p-3 text-left transition hover:bg-stone-50"><span><span className="block text-sm font-semibold">{r.name}{r.id===data.recipients[0]?.id?" · Principal":""}</span><span className="mt-1 block text-xs text-navy-500">{r.phone}</span><span className="mt-1 block text-xs text-navy-500">{a?a.street+" "+a.exteriorNumber+", "+a.municipality:"Sin dirección"}</span></span>{r.id===value&&<Check className="size-4 text-brand-700"/>}</button>;})}{!found.length&&<p className="py-4 text-sm text-navy-500">No hay coincidencias.</p>}{found.length>30&&<p className="text-xs text-navy-500">Mostrando 30 resultados. Refina la búsqueda.</p>}</div><button type="button" className="inline-flex items-center justify-center gap-2 rounded-xl border border-dashed border-stone-300 p-3 text-sm font-semibold text-navy-700 hover:bg-stone-50" onClick={()=>{setChoosing(false);start();}}><Plus className="size-4"/>Agregar destinatario</button></div>
 </Dialog>
 {message&&!open&&<p role="status" className="text-sm text-orange-700">{message}</p>}
 <Dialog open={open} onClose={()=>{if(!busy)setOpen(false);}} title={person.id?"Editar destinatario":"Agregar destinatario"} description="Guarda la persona y su dirección sin salir de recepción." size="large">
 <form className="grid max-h-[65vh] gap-4 overflow-y-auto pr-2" onSubmit={async e=>{e.preventDefault();e.stopPropagation();if(busy)return;setBusy(true);setMessage("");try{const r=await upsertCustomerRecipient(userId,person,person.id||undefined,newAddress?address:undefined);if(!active.current)return;if(!r.ok){setMessage(r.error);return;}setData(d=>({...d,recipients:d.recipients.some(p=>p.id===r.recipient.id)?d.recipients.map(p=>p.id===r.recipient.id?r.recipient:p):[...d.recipients,r.recipient],addresses:r.address?[...d.addresses.filter(a=>a.id!==r.address!.id),r.address]:d.addresses}));onChange(r.recipient.id);setQuery("");setOpen(false);setMessage("Destinatario guardado y seleccionado para estos paquetes.");}catch{setMessage("No se pudo confirmar el guardado. Revisa la conexión antes de reintentar.");}finally{setBusy(false);}}}>
 <fieldset disabled={busy} className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2"><Input name="recipientName" label="Nombre completo de quien recibe" required value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/><Input name="recipientPhone" label="Teléfono de quien recibe" type="tel" required value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/></div>
 <Select label="Dirección de entrega" value={newAddress?"new":"existing"} options={[...(data.addresses.length?[{value:"existing",label:"Seleccionar dirección guardada"}]:[]),{value:"new",label:"Registrar una nueva dirección"}]} onChange={e=>setNewAddress(e.target.value==="new")}/>
 {newAddress?<div className="grid gap-3 sm:grid-cols-2">{fields.map(([name,label,required])=><Input key={name} name={"address-"+name} label={label} required={required} value={address[name]} maxLength={name==="postalCode"?5:name==="references"?300:undefined} inputMode={name==="postalCode"?"numeric":undefined} onChange={e=>setAddress({...address,[name]:e.target.value})}/>)}</div>:<Select label="Dirección guardada" required value={person.addressId} options={[{value:"",label:"Selecciona dirección"},...data.addresses.map(a=>({value:a.id,label:a.label+" · "+a.street+" "+a.exteriorNumber+", "+a.municipality+", "+a.state}))]} onChange={e=>setPerson({...person,addressId:e.target.value})}/>}
 </fieldset>{message&&<p role="alert" className="text-sm text-orange-700">{message}</p>}<div className="flex flex-wrap justify-end gap-2">{person.id&&<button type="button" disabled={busy} className="mr-auto inline-flex items-center gap-1.5 px-2 text-xs text-red-700" onClick={async()=>{if(!window.confirm("¿Eliminar este destinatario? Se conservará si tiene paquetes o envíos vinculados."))return;setBusy(true);try{const r=await deleteCustomerRecipient(userId,person.id);if(!active.current)return;if(!r.ok){setMessage(r.error);return;}setData(d=>({...d,recipients:d.recipients.filter(p=>p.id!==person.id)}));onChange("");setOpen(false);setChoosing(true);}catch{setMessage("No se confirmó la eliminación.");}finally{setBusy(false);}}}><Trash2 className="size-3.5"/>Eliminar contacto</button>}<Button type="button" variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" loading={busy}>Guardar destinatario</Button></div>
 </form></Dialog></div>;
}
