"use client";
import { warehouseSupports } from "@/lib/config/warehouses";
import { useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { saveTruckStops, scanLoad } from "@/lib/auth/warehouse-actions";
import type { Truck, Warehouse } from "@/lib/types";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
export function TruckRoute({truck,warehouses}:{truck:Truck;warehouses:Warehouse[]}){
 const router=useRouter(),scanner=useRef<HTMLInputElement>(null);
 const [stops,setStops]=useState((truck.stops??[]).map(s=>({warehouseId:s.warehouseId,arrivalDate:s.arrivalDate}))),[destination,setDestination]=useState(truck.stops?.[0]?.warehouseId??""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const origins=warehouses.filter(w=>w.active&&warehouseSupports(w,"origen"));
 const [origin,setOrigin]=useState(truck.originWarehouseId??(origins.length===1?origins[0].id:""));
 const editable=["planificado","cargando"].includes(truck.status);
 async function execute(kind:"route"|"scan") {setBusy(true);try{const result=await(kind==="route"?saveTruckStops(truck.id,stops,origin):scanLoad(truck.id,code,destination));if(!result.ok){setMessage(result.error);return;}setMessage(kind==="route"?"Paradas y fechas guardadas.":`Paquete ${code} cargado.`);if(kind==="scan")setCode("");else setDestination(stops[0]?.warehouseId??"");router.refresh();}catch{setMessage("No se pudo guardar. Revisa el estado antes de reintentar.");}finally{setBusy(false);if(kind==="scan")scanner.current?.focus();}}
 return <section className="mb-7 grid gap-5 rounded-3xl border border-stone-200 bg-white p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Ruta y control físico</p><h2 className="mt-2 font-display text-2xl font-bold">Un viaje, múltiples destinos</h2><p className="mt-2 text-sm text-navy-500">Ordena las paradas por fecha de llegada. No puedes quitar un destino con paquetes cargados.</p></div>
 <form onSubmit={e=>{e.preventDefault();void execute("route");}} className="grid gap-3"><Select label="Almacén de origen · salida del viaje" required disabled={!editable||truck.boxIds.length>0} value={origin} options={[{value:"",label:"Selecciona el almacén de salida"},...warehouses.filter(w=>(w.active&&warehouseSupports(w,"origen"))||w.id===truck.originWarehouseId).map(w=>({value:w.id,label:`${w.name} · ${w.city}`}))]} onChange={e=>setOrigin(e.target.value)}/>{stops.map((stop,index)=><div key={index} className="grid items-end gap-3 rounded-xl bg-cream-50 p-3 md:grid-cols-[1fr_1fr_auto]"><Select label={`Almacén · parada ${index+1}`} disabled={!editable} value={stop.warehouseId} options={[{value:"",label:"Selecciona almacén"},...warehouses.filter(w=>(w.active&&warehouseSupports(w,"destino")&&w.id!==origin)||w.id===stop.warehouseId).map(w=>({value:w.id,label:`${w.name} · ${w.city}`}))]} onChange={e=>setStops(stops.map((s,i)=>i===index?{...s,warehouseId:e.target.value}:s))}/><Input label="Llegada estimada" type="date" required min={truck.departureDate} disabled={!editable} value={stop.arrivalDate} onChange={e=>setStops(stops.map((s,i)=>i===index?{...s,arrivalDate:e.target.value}:s))}/><Button type="button" variant="ghost" disabled={!editable} onClick={()=>setStops(stops.filter((_,i)=>i!==index))}>Quitar</Button></div>)}{editable&&<div className="flex flex-wrap gap-3"><Button type="button" variant="secondary" onClick={()=>setStops([...stops,{warehouseId:"",arrivalDate:stops.at(-1)?.arrivalDate??truck.departureDate}])}>Agregar destino</Button><Button type="submit" loading={busy}>Guardar ruta</Button></div>}</form>
 {!warehouses.length&&<p className="text-sm text-orange-700">Crea los almacenes en «Almacenes y operadores» antes de configurar este viaje.</p>}
 {editable&&<form onSubmit={e=>{e.preventDefault();void execute("scan");}} className="grid gap-4 rounded-2xl bg-navy-950 p-5 text-white md:grid-cols-[1fr_1fr_auto]"><Select tone="dark" label="Destino del paquete" value={destination} options={[{value:"",label:"Selecciona parada guardada"},...(truck.stops??[]).map(s=>({value:s.warehouseId,label:warehouses.find(w=>w.id===s.warehouseId)?.name??s.city}))]} onChange={e=>setDestination(e.target.value)}/><Input ref={scanner} tone="dark" label="Escanear paquete" required autoComplete="off" placeholder="BX-…" value={code} onChange={e=>setCode(e.target.value)}/><Button type="submit" className="self-end" loading={busy} disabled={truck.status!=="cargando"||!destination}>Registrar carga</Button><p className="text-xs text-white/65 md:col-span-3">Primero guarda la ruta e inicia la carga. Utiliza el lector en modo teclado + Enter; cada código se verifica contra el envío y la capacidad disponible.</p></form>}
 <p role="status" aria-live="polite" className="text-sm font-semibold">{message}</p></section>;
}
