'use client';
import Link from 'next/link';
import {ArrowUpRight,Download,Package,Smartphone,MapPin,Check} from 'lucide-react';
import {usePwa} from './pwa-provider';
import {PushSettings} from './push-settings';
export function AppPromotion({compact=false}:{compact?:boolean}){
 const {installed,available,busy,ios,message,install}=usePwa();
 return <section id={compact?'app-cliente':'app'} aria-label="App de A&L" className={compact?'mt-7':'bg-cream-100 px-5 py-20 sm:px-8 lg:px-18'}><div className={`relative mx-auto overflow-hidden rounded-3xl bg-navy-950 text-white ${compact?'p-6 sm:p-8':'grid max-w-[90rem] gap-12 p-8 sm:p-12 lg:grid-cols-[1.2fr_.8fr] lg:p-16'}`}>
  <div className="relative z-10 max-w-2xl"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-orange-300"><Smartphone className="size-4"/>A&L en tu dispositivo</p><h2 className={`mt-4 font-display font-bold tracking-tight ${compact?'text-2xl sm:text-3xl':'text-4xl sm:text-5xl'}`}>{compact?'Tu panel, a un toque.':'Tus envíos te acompañan.'}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">{compact?'Agrega A&L a tu pantalla de inicio y entra a tus paquetes, facturas y destinatarios desde un solo lugar.':'Instala nuestra app web (PWA) directamente desde el navegador. Consulta tus paquetes, organiza tus destinatarios y revisa tus facturas con la misma cuenta de siempre.'}</p>
  <div className="mt-6 flex flex-wrap items-center gap-3">{installed?<span className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm"><Check className="size-4 text-orange-300"/>App instalada</span>:available?<button type="button" disabled={busy} onClick={install} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 text-sm font-semibold text-navy-950 transition hover:bg-orange-100 disabled:opacity-60"><Download className="size-4"/>{busy?'Abriendo instalación…':'Instalar app de A&L'}</button>:null}{!compact&&<Link href="/cliente" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/25 px-5 text-sm font-semibold hover:bg-white/10">Abrir mi panel<ArrowUpRight className="size-4"/></Link>}</div>
  {!installed&&<details className="mt-4 max-w-lg rounded-xl border border-white/15 bg-white/5 p-4"><summary className="cursor-pointer text-sm font-medium">{available?'Otras formas de instalar':'Cómo instalar en mi dispositivo'}</summary><div className="mt-3 space-y-3 text-sm leading-6 text-slate-300">{ios?<p>En iPhone o iPad, abre este sitio en Safari. Pulsa <strong className="text-white">Compartir → Agregar a pantalla de inicio</strong> y confirma. Si aparece, activa «Abrir como app web».</p>:<><p><strong className="text-white">Android / Chrome / Edge:</strong> abre el menú del navegador y busca «Instalar aplicación» o «Agregar a pantalla de inicio».</p><p><strong className="text-white">iPhone / iPad:</strong> abre en Safari y elige Compartir → Agregar a pantalla de inicio.</p><p><strong className="text-white">Safari en Mac:</strong> si está disponible, usa Archivo → Agregar al Dock.</p></>}<p>Si no aparece la opción, prueba un navegador compatible actualizado. No necesitas una tienda de aplicaciones.</p></div></details>}
  {message&&<p role="status" className="mt-3 text-sm text-orange-200">{message}</p>}<p className="mt-4 text-xs leading-5 text-slate-400">Requiere conexión a internet. Las notificaciones son opcionales y necesitan tu permiso.</p>{compact&&<PushSettings/>}</div>
  {!compact&&<div aria-hidden="true" className="relative flex items-center justify-center"><div className="absolute size-64 rounded-full bg-orange-500/15 blur-3xl"/><div className="relative w-full max-w-72 rotate-3 rounded-[2.5rem] border border-white/20 bg-slate-900 p-4 shadow-2xl"><div className="mx-auto mb-5 h-1 w-12 rounded-full bg-slate-600"/><div className="rounded-[1.6rem] bg-[#faf8f4] p-5 text-navy-950"><span className="font-display text-xl font-extrabold">A&L<span className="text-orange-600">.</span></span><p className="mt-6 text-xs text-slate-500">Siempre cerca</p><p className="mt-1 text-xl font-bold">Todo bajo control.</p>{[[Package,'Mis paquetes','Consulta cada avance'],[MapPin,'Destinatarios','Tus contactos de entrega']].map(([Icon,title,subtitle])=>{const Glyph=Icon as typeof Package;return <div key={String(title)} className="mt-4 rounded-xl border border-stone-200 bg-white p-4"><Glyph className="mb-3 size-5 text-orange-600"/><p className="text-sm font-semibold">{String(title)}</p><p className="mt-1 text-xs text-slate-500">{String(subtitle)}</p></div>;})}<p className="mt-5 text-[10px] uppercase tracking-widest text-slate-400">Vista ilustrativa</p></div></div></div>}
 </div></section>;
}
