import Link from "next/link";
import { ArrowLeft, Download } from "lucide-react";
import { SectionTitle } from "@/components/cliente/section-title";
import { PaymentForm } from "@/components/cliente/payment-form";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/badge";
import { getBoxCategory } from "@/lib/config/box-categories";
import { logisticsService } from "@/lib/services/logistics";
import { formatUsd } from "@/lib/utils/format";
import { invoiceSubtotal, invoiceTotal } from "@/lib/utils/invoices";

export default async function InvoiceDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const invoice = (await logisticsService.getInvoices()).find((item) => item.id === id); if (!invoice) return <p>Factura no encontrada.</p>; const total = invoiceTotal(invoice); return <><Link href="/cliente/facturas" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-navy-500"><ArrowLeft className="size-4" />Mis facturas</Link><SectionTitle eyebrow="Detalle de factura" title={invoice.number} action={<div className="flex items-center gap-3"><StatusBadge status={invoice.status} /><a href={`/api/facturas/${invoice.id}/pdf`} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-navy-950 px-5 text-sm font-bold text-white"><Download className="size-4" />Descargar PDF</a></div>} /><div className="mt-7 grid gap-5 lg:grid-cols-[1.1fr_.7fr]"><Card className="shadow-none"><h2 className="font-display text-xl font-bold">Desglose</h2><div className="mt-5 divide-y divide-stone-200">{invoice.lines.map((line) => <div key={line.categoryId} className="flex justify-between gap-4 py-4"><div><p className="font-bold text-navy-900">{line.quantity} × {getBoxCategory(line.categoryId)?.name}</p><p className="mt-1 text-xs text-navy-500">{formatUsd(line.unitPriceUsd)} cada una</p></div><p className="font-bold">{formatUsd(line.quantity * line.unitPriceUsd)}</p></div>)}</div><dl className="mt-5 grid gap-3 border-t-2 border-navy-950 pt-5 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{formatUsd(invoiceSubtotal(invoice))}</dd></div><div className="flex justify-between"><dt>Seguro opcional</dt><dd>{formatUsd(invoice.insuranceUsd)}</dd></div><div className="flex justify-between"><dt>Entrega a domicilio</dt><dd>{formatUsd(invoice.homeDeliveryUsd)}</dd></div><div className="flex justify-between font-display text-xl font-bold"><dt>Total</dt><dd className="text-orange-600">{formatUsd(total)}</dd></div></dl></Card><Card className="h-fit shadow-none"><h2 className="font-display text-xl font-bold">Reportar pago</h2><p className="mt-2 text-sm leading-6 text-navy-500">Adjunta los datos del pago para revisión.</p><div className="mt-5"><PaymentForm amount={total} /></div></Card></div></>; }
