import { EmailControls } from "@/components/admin/email-controls";
import { siteUrl } from "@/lib/services/email";
import Link from "@/components/admin/admin-access";
import type { RowDataPacket } from "mysql2/promise";
import { pool } from "@/lib/db/pool";
import { requireAdminUser } from "@/lib/auth/actions";
import { SectionTitle } from "@/components/cliente/section-title";
export default async function EmailsPage() {
  await requireAdminUser(["correos"]);
  const [rows] = await pool().query<RowDataPacket[]>("SELECT id,status,attempts,created_at,last_error FROM email_outbox ORDER BY created_at DESC LIMIT 100");
  const preview = process.env.NODE_ENV !== "production" && process.env.EMAIL_DELIVERY === "preview";
  const labels: Record<string,string> = {queued:"En cola",retry:"Reintentando",sent:"Aceptado por Resend",delivered:"Entregado",failed:"Fallido",bounced:"Rebotado",complained:"Marcado como spam"};
  return <><SectionTitle eyebrow="Comunicación" title="Cada mensaje, bajo control." description="Estado de los últimos 100 correos transaccionales. Aceptado por Resend no significa entregado." /><EmailControls keyPresent={Boolean(process.env.RESEND_API_KEY)} from={process.env.RESEND_FROM_EMAIL??""} mode={process.env.EMAIL_DELIVERY??"preview"} webhook={Boolean(process.env.RESEND_WEBHOOK_SECRET)} site={siteUrl()} /><div className="mt-6 rounded-2xl border border-line-300 bg-white p-5"><p className="text-sm text-ink-700">{preview ? "Vista previa local: los mensajes se guardan, pero no se envían a destinatarios reales." : "Entrega mediante Resend. Los reintentos se procesan con el worker de correo."}</p><div className="mt-4 flex flex-wrap gap-3">{["verify","welcome","reset","changed","invite","invoice","reception","payment","delivery","support"].map((kind,index) => <Link key={kind} target="_blank" href={`/api/emails/preview?template=${kind}`} className="rounded-full border border-line-300 px-4 py-2 text-xs font-semibold">{["Verificación","Bienvenida","Recuperación","Contraseña cambiada","Invitación","Factura","Recepción","Pago","Entrega","Soporte"][index]}</Link>)}</div></div><div className="mt-6 overflow-x-auto rounded-2xl border border-line-300 bg-white"><table className="w-full min-w-[550px] text-left text-sm"><thead className="bg-cream-100"><tr>{["Fecha","Estado","Intentos","Detalle"].map(label=><th key={label} className="p-4 font-semibold">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-line-300"><td className="p-4">{new Date(row.created_at).toLocaleString("es-MX")}</td><td className="p-4">{labels[row.status] ?? row.status}</td><td className="p-4">{row.attempts}</td><td className="p-4">{preview && row.status === "queued" ? <Link target="_blank" className="font-semibold text-brand-700" href={`/api/emails/preview?id=${row.id}`}>Abrir correo local</Link> : row.last_error ? "Revisar remitente y configuración de Resend" : "—"}</td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center text-sm text-ink-700">Los correos aparecerán aquí al crear cuentas o realizar operaciones.</p>}</div></>;
}
