import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Clock3, MapPin, PackageCheck, ShieldCheck, ShoppingBag, Truck, X } from "lucide-react";
import { FaqList } from "@/components/marketing/faq-list";
import { MarketingFooter } from "@/components/marketing/marketing-footer";
import { MarketingHeader } from "@/components/marketing/marketing-header";
import { QuoteCalculator } from "@/components/marketing/quote-calculator";
import { TrackingSearch } from "@/components/marketing/tracking-search";
import { TruckIllustration } from "@/components/marketing/truck-illustration";
import { BoxMark } from "@/components/marketing/box-mark";
import { DESTINATION_COVERAGE } from "@/lib/config/company";
import { configService } from "@/lib/services/config";
import { formatUsd } from "@/lib/utils/format";

export const metadata: Metadata = {
  title: "Envíos terrestres USA a México",
  description: "Envía desde USA a México con precio fijo por categoría de caja. Cotiza y rastrea sin sorpresas.",
  openGraph: { title: "Envía más, paga menos | A&L Trucking Logistics", description: "Precio fijo por categoría de caja para envíos terrestres USA → México.", type: "website" },
};

export default async function LandingPage() {
  const [flow, categories] = await Promise.all([configService.getFlowConfig(), configService.getRateTable()]);
  const steps = flow.originMode === "casillero"
    ? [{ icon: ShoppingBag, title: "Compra en línea", body: "Usa tu casillero A&L al comprar en tiendas de USA." }, { icon: PackageCheck, title: "Pre-alerta", body: "Registra el tracking para identificar tu compra al recibirla." }, { icon: Truck, title: "Agrupa y envía", body: "Elige tus cajas disponibles y confirma el envío a México." }, { icon: MapPin, title: "Recibe en México", body: "Sigue cada etapa hasta la entrega seleccionada." }]
    : [{ icon: PackageCheck, title: "Prepara tu caja", body: "Empaca una caja firme, sellada y con forma cuadrada." }, { icon: MapPin, title: "Entrega o solicita recolección", body: "Coordina el ingreso de tu caja con la agencia." }, { icon: Truck, title: "Viaja a México", body: "La caja se asigna a un camión y comienza su ruta." }, { icon: ShieldCheck, title: "Recibe con confianza", body: "Sigue el trayecto hasta la entrega seleccionada." }];

  return <>
    <MarketingHeader />
    <main>
      <section className="relative overflow-hidden bg-cream-100"><div aria-hidden="true" className="absolute -right-40 -top-40 size-[38rem] rounded-full border-[7rem] border-white/45" /><div className="relative mx-auto grid max-w-7xl items-center gap-8 px-5 pb-16 pt-12 sm:px-8 sm:pt-20 lg:grid-cols-[1.05fr_.95fr] lg:pb-24"><div><p className="inline-flex items-center gap-2 rounded-full border border-stone-200 bg-white/65 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-navy-700"><span className="size-2 rounded-full bg-orange-500" />Carga terrestre · USA → México</p><h1 className="mt-7 max-w-3xl font-display text-5xl font-extrabold leading-[.97] tracking-[-.06em] text-navy-950 sm:text-6xl lg:text-[5.5rem]">Envía más,<br /><span className="text-orange-500">paga menos.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-navy-500">Precio fijo por categoría de caja. Conoce el total desde el inicio y sigue cada movimiento hasta México.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/registro" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-navy-950 px-6 text-sm font-bold text-white shadow-lift transition hover:-translate-y-0.5 hover:bg-navy-800">Crear mi cuenta <ArrowRight className="size-4" /></Link><Link href="#tarifas" className="inline-flex min-h-12 items-center rounded-full border border-stone-200 bg-white px-6 text-sm font-bold text-navy-800 transition hover:border-navy-400">Ver tarifas</Link></div><div className="mt-8 flex flex-wrap gap-x-7 gap-y-2 text-sm text-navy-600"><span className="flex items-center gap-2"><Check className="size-4 text-success-700" />5 categorías claras</span><span className="flex items-center gap-2"><Check className="size-4 text-success-700" />Sin cobros silenciosos</span></div></div><div className="relative mx-auto w-full max-w-2xl"><div className="absolute inset-12 translate-y-16 rounded-full bg-orange-500/15 blur-3xl" /><TruckIllustration /></div></div></section>
      <section className="relative z-10 mx-auto -mt-7 max-w-4xl px-5 sm:px-8"><div className="rounded-[1.8rem] bg-navy-950 p-5 shadow-lift sm:p-7"><div className="mb-4 flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-500">Rastreo público</p><h2 className="mt-1 font-display text-lg font-bold text-white">¿Dónde está tu carga?</h2></div><p className="hidden text-xs text-white/45 sm:block">Consulta sin iniciar sesión</p></div><TrackingSearch dark /></div></section>
      <section id="tarifas" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><SectionHeading eyebrow="Tarifas transparentes" title="Una caja. Un precio fijo." description="El peso es un límite de seguridad, no la unidad de cobro. Elige la categoría más pequeña que admita todas tus medidas y el peso total." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.map((category, index) => <article key={category.id} className={`group relative overflow-hidden rounded-card border bg-white p-5 transition duration-200 hover:-translate-y-1 hover:shadow-lift ${index === 1 ? "border-orange-500 shadow-soft" : "border-stone-200"}`}>{index === 1 && <span className="absolute right-4 top-4 rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-orange-600">Popular</span>}<div className="mx-auto mt-5 w-[72%] transition group-hover:scale-105"><BoxMark /></div><h3 className="mt-5 font-display text-xl font-bold text-navy-950">{category.name}</h3><p className="mt-2 font-display text-2xl font-extrabold text-orange-500">{formatUsd(category.priceUsd)}</p><div className="mt-5 border-t border-stone-200 pt-4 text-xs leading-6 text-navy-500"><p>{category.dimensions.length} × {category.dimensions.width} × {category.dimensions.height} in</p><p>Hasta {category.maxWeightLb} lb</p></div></article>)}</div></section>
      <section className="bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><SectionHeading eyebrow="Cotizador rápido" title="Mide, pesa y descubre tu categoría." description="Prueba combinaciones en vivo. Si una caja supera el catálogo, te lo diremos antes de cualquier cobro." /><QuoteCalculator /></div></section>
      <section id="como-funciona" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><SectionHeading eyebrow="Cómo funciona" title="De USA a tu destino, paso a paso." description={flow.originMode === "casillero" ? "Compra en tus tiendas favoritas y usa tu casillero personal A&L." : "Entrega tu caja a la agencia y nosotros coordinamos el recorrido."} /><div className="mt-12 grid gap-px overflow-hidden rounded-card border border-stone-200 bg-stone-200 md:grid-cols-4">{steps.map((step, index) => <article key={step.title} className="bg-white p-6"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-orange-50 text-orange-600"><step.icon className="size-5" /></span><span className="font-display text-sm font-bold text-navy-300">0{index + 1}</span></div><h3 className="mt-6 font-display text-lg font-bold text-navy-950">{step.title}</h3><p className="mt-2 text-sm leading-6 text-navy-500">{step.body}</p></article>)}</div></section>
      <section className="bg-navy-950 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-500">Cómo enviar tu caja</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em] sm:text-5xl">La forma importa tanto como el contenido.</h2><p className="mt-5 max-w-lg leading-7 text-white/60">Una caja bien preparada protege tus artículos y mantiene el proceso en movimiento.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-card bg-white p-6 text-navy-950"><span className="grid size-11 place-items-center rounded-2xl bg-success-50 text-success-700"><Check className="size-5" /></span><h3 className="mt-6 font-display text-xl font-bold">Así debe viajar</h3><ul className="mt-4 grid gap-3 text-sm text-navy-600"><li>Caja firme y bien empacada</li><li>Sellada en todas sus uniones</li><li>Conserva su forma cuadrada</li></ul></article><article className="rounded-card border border-white/15 bg-white/5 p-6"><span className="grid size-11 place-items-center rounded-2xl bg-danger-50 text-danger-700"><X className="size-5" /></span><h3 className="mt-6 font-display text-xl font-bold">No puede viajar</h3><ul className="mt-4 grid gap-3 text-sm text-white/60"><li>Caja dañada o rota</li><li>Cartón húmedo o debilitado</li><li>Caja deformada o abierta</li></ul></article></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid overflow-hidden rounded-[2rem] border border-stone-200 bg-cream-100 lg:grid-cols-[.9fr_1.1fr]"><div className="p-7 sm:p-10"><SectionHeading eyebrow="Cobertura demo" title="Miami conecta con México." description="Las zonas y los tiempos son datos por confirmar con el cliente antes de producción." /><div className="mt-8 grid gap-2 sm:grid-cols-2">{DESTINATION_COVERAGE.map((item) => <div key={item.region} className="flex items-center justify-between gap-3 rounded-xl bg-white px-4 py-3"><span className="text-sm font-semibold text-navy-800">{item.region}</span><Clock3 className="size-4 text-orange-500" /></div>)}</div></div><div className="relative min-h-80 overflow-hidden bg-navy-950 p-8"><svg viewBox="0 0 600 360" className="absolute inset-0 h-full w-full" aria-label="Ruta esquemática de Miami a México" role="img"><path d="M78 80 C230 30 304 144 506 263" fill="none" stroke="#ffffff" strokeOpacity=".12" strokeWidth="62" strokeLinecap="round" /><path d="M78 80 C230 30 304 144 506 263" fill="none" stroke="#E8621C" strokeWidth="5" strokeDasharray="12 12" strokeLinecap="round" /><circle cx="78" cy="80" r="13" fill="#fff" /><circle cx="506" cy="263" r="13" fill="#E8621C" /><text x="55" y="54" fill="#fff" fontSize="18" fontWeight="700">Miami</text><text x="449" y="304" fill="#fff" fontSize="18" fontWeight="700">México</text></svg></div></div></section>
      <section id="faq" className="bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Preguntas frecuentes" title="Antes de enviar, todo claro." description="Si tu pregunta no aparece aquí, el centro de soporte estará disponible dentro de tu cuenta." /><FaqList /></div></section>
    </main>
    <MarketingFooter />
  </>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-600">{eyebrow}</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.045em] text-navy-950 sm:text-5xl">{title}</h2><p className="mt-5 text-base leading-7 text-navy-500">{description}</p></div>;
}
