import Link from "next/link";
import type { ReactNode } from "react";
import { Bell, BookOpen, Boxes, Calculator, CircleDollarSign, ClipboardList, FileText, Headphones, Home, MapPinned, PackagePlus, Settings, Truck, UserRound, UsersRound } from "lucide-react";
import { Sidebar, type SidebarItem } from "@/components/ui/sidebar";
import { signOut } from "@/lib/auth/actions";

const baseItems: SidebarItem[] = [
  { label: "Inicio", href: "/cliente", icon: Home }, { label: "Mis cajas", href: "/cliente/cajas", icon: Boxes }, { label: "Mis envíos", href: "/cliente/envios", icon: Truck }, { label: "Crear envío", href: "/cliente/envios/nuevo", icon: PackagePlus }, { label: "Cotizador", href: "/cliente/cotizador", icon: Calculator }, { label: "Direcciones", href: "/cliente/direcciones", icon: MapPinned }, { label: "Destinatarios", href: "/cliente/destinatarios", icon: UsersRound }, { label: "Mis facturas", href: "/cliente/facturas", icon: FileText }, { label: "Estado de cuenta", href: "/cliente/estado-cuenta", icon: CircleDollarSign }, { label: "Notificaciones", href: "/cliente/notificaciones", icon: Bell }, { label: "Soporte", href: "/cliente/soporte", icon: Headphones }, { label: "Ayuda", href: "/cliente/ayuda", icon: BookOpen }, { label: "Cuenta", href: "/cliente/cuenta", icon: UserRound },
];

export function ClientShell({ children, originMode, userName, lockerCode }: { children: ReactNode; originMode: "casillero" | "entrega-directa"; userName: string; lockerCode: string }) {
  const items = originMode === "casillero" ? [...baseItems.slice(0, 4), { label: "Pre-alertas", href: "/cliente/pre-alertas", icon: ClipboardList }, ...baseItems.slice(4)] : baseItems;
  return <main className="min-h-screen bg-cream-100 p-3 sm:p-5 lg:p-6"><div className="mx-auto grid max-w-[1600px] gap-5 lg:grid-cols-[18rem_1fr]"><div className="hidden lg:block"><div className="sticky top-6 h-[calc(100vh-3rem)]"><Sidebar items={items} footer={<div><p className="text-sm font-bold text-white">{userName}</p><p className="mt-1 text-xs text-white/50">{lockerCode}</p><form action={signOut}><button className="mt-4 text-xs font-semibold text-orange-400">Cerrar sesión</button></form></div>} /></div></div><div className="min-w-0"><header className="mb-4 flex items-center justify-between rounded-2xl bg-white px-4 py-3 shadow-soft lg:hidden"><Link href="/cliente" className="font-display font-extrabold text-navy-950">A&L <span className="text-orange-500">Cliente</span></Link><details className="relative"><summary className="grid size-10 cursor-pointer list-none place-items-center rounded-full bg-navy-950 text-white"><Settings className="size-4" /></summary><nav className="absolute right-0 top-12 z-40 max-h-[70vh] w-72 overflow-y-auto rounded-2xl border border-stone-200 bg-white p-2 shadow-lift">{items.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-navy-700 hover:bg-cream-100"><Icon className="size-4 text-orange-500" />{label}</Link>)}</nav></details></header><section className="min-h-[calc(100vh-3rem)] rounded-[1.8rem] border border-stone-200/70 bg-cream-50 p-5 shadow-[0_20px_70px_rgba(28,43,75,.07)] sm:p-8 lg:p-10">{children}</section></div></div></main>;
}
