import type { FlowConfig } from "@/lib/config/flow";
import type { BoxStatus, ShipmentStatus, TruckStatus, InvoiceStatus, SupportStatus } from "@/lib/types";

export type GuideTrack = "envio" | "pagos" | "soporte";
export type GuideStep = {
  id: string; title: string; summary: string;
  client: string; admin: string; system: string;
  guard: string; notification: string;
  box?: BoxStatus; shipment?: ShipmentStatus; truck?: TruckStatus;
  invoice?: InvoiceStatus; support?: SupportStatus;
};

// Public educational content only. No customer data or mutations belong here.
export function getFlowGuide(flow: FlowConfig, track: GuideTrack): GuideStep[] {
  const delivery = flow.deliveryMode === "sucursal" ? "en sucursal" : flow.deliveryMode === "domicilio" ? "a domicilio" : "en sucursal o a domicilio, según la opción elegida";
  const billing = flow.billingMoment === "al-recibir" ? "al registrar la recepción" : "al despachar el camión";
  if (track === "pagos") return [
    {id:"factura",title:"Factura emitida",summary:`La factura nace ${billing}, o en recepción al registrar la forma de pago.`,client:"Consulta el desglose y el total en Mis facturas.",admin:"La recepción o el despacho genera la factura según la configuración. Registrar efectivo, tarjeta o pago en destino en bodega emite la factura en recepción.",system:"Conserva el precio de cada línea facturada. Un cambio posterior del tarifario no modifica esa factura.",guard:"No factura dos veces la misma caja en el despacho. La cotización no sustituye la factura.",notification:"Notificación de factura disponible; el evento de recepción o despacho también genera un correo en cola.",invoice:"emitida"},
    {id:"destino",title:"Pago en destino",summary:"El acuerdo de cobro no es un pago recibido.",client:"Consulta el saldo pendiente y el comprobante del acuerdo.",admin:"Selecciona Pago en destino en recepción. Al cobrar, abre la factura y confirma efectivo o tarjeta con el comprobante real.",system:"Conserva el saldo hasta registrar el cobro; una caja entregada no liquida la factura.",guard:"El comprobante del acuerdo no marca la factura como pagada. No se puede cobrar dos veces.",notification:"Aviso de pago pendiente en destino.",invoice:"pendiente-pago-destino"},
    {id:"reporte",title:"Cliente reporta",summary:"Reportar un pago no significa que esté aprobado.",client:"Captura el importe total, método y referencia bancaria.",admin:"Encuentra el reporte en Facturas y en la bandeja de pendientes.",system:"Valida titularidad de la factura e importe exacto antes de enviarlo a revisión.",guard:"No procesa cargos de tarjeta ni abonos parciales. Operaciones registra cobros ya realizados con comprobantes privados.",notification:"Notificación y correo en cola al recibir el reporte.",invoice:"pago-reportado"},
    {id:"revision",title:"Equipo verifica",summary:"El administrador contrasta el reporte con el pago real.",client:"Espera la resolución en su panel.",admin:"Aprueba con una nota o rechaza explicando el motivo.",system:"Si se rechaza, vuelve a Emitida y permite un nuevo reporte. No inventa una confirmación bancaria.",guard:"Un reporte incorrecto no puede aprobarse. Las validaciones de servidor también se aplican al administrador.",notification:"Aprobación o rechazo genera notificación y correo en cola.",invoice:"pago-reportado"},
    {id:"pagada",title:"Factura pagada",summary:"La validación administrativa cierra el saldo de esa factura.",client:"Ve la factura pagada y su estado de cuenta actualizado.",admin:"Conserva el registro de revisión y el historial.",system:"Evita aprobar dos veces la misma factura. No cambia el estado físico de las cajas.",guard:"Pago y transporte son flujos independientes; actualmente no hay un bloqueo automático de entrega por deuda.",notification:"El estado Pagada queda visible para el cliente.",invoice:"pagada"},
  ];
  if (track === "soporte") return [
    {id:"consulta",title:"Cliente consulta",summary:"La conversación queda ligada a la cuenta, no a un chat externo.",client:"Abre un ticket con asunto y detalle desde Soporte.",admin:"Ve la consulta en la bandeja de soporte y en Pendientes.",system:"Persiste el ticket y limita su acceso al titular y al equipo autorizado.",guard:"Un cliente no puede leer ni responder consultas ajenas.",notification:"Confirmación al cliente mediante notificación y correo en cola.",support:"abierto"},
    {id:"respuesta",title:"Equipo responde",summary:"Ambos paneles comparten la misma conversación.",client:"Lee la respuesta en su panel; puede actualizar la conversación.",admin:"Responde y decide si mantener abierto o pasar a revisión.",system:"Detecta cambios simultáneos para no sobrescribir una respuesta nueva.",guard:"Las respuestas son visibles al cliente. Las notas internas del perfil no pertenecen al ticket.",notification:"Una respuesta del equipo genera una notificación y un correo en cola.",support:"en-revision"},
    {id:"seguimiento",title:"Dar seguimiento",summary:"Una nueva respuesta del cliente devuelve el ticket a Abierto.",client:"Añade información mientras el ticket no esté cerrado.",admin:"Retoma la conversación desde Pendientes.",system:"Conserva los mensajes, autor y fecha. El panel identifica si el cliente espera respuesta.",guard:"La actualización se consulta al refrescar; no se presenta como chat en tiempo real.",notification:"La respuesta del cliente queda en el ticket; no hay email automático al equipo en esta versión.",support:"abierto"},
    {id:"cierre",title:"Cerrar o reabrir",summary:"Cerrar una consulta no elimina su historial.",client:"Puede consultar la conversación cerrada o abrir una nueva consulta.",admin:"Cierra el ticket o lo reabre antes de continuar respondiendo.",system:"Impide respuestas a tickets cerrados y registra quién gestionó el cambio.",guard:"El cliente no puede reabrir un ticket por su cuenta.",notification:"El cambio de estado genera notificación y correo en cola al cliente.",support:"cerrado"},
  ];
  return [
    {id:"cuenta",title:"Activa tu cuenta",summary:"Una identidad, un casillero y acceso privado a tu operación.",client:"Se registra, confirma su correo y entra con correo o casillero y contraseña.",admin:"También puede dar de alta a un cliente y enviarle una invitación para definir su contraseña.",system:"Asigna el casillero y valida cuenta activa, correo confirmado y rol en el servidor.",guard:"Una cuenta sin verificar no accede al panel. Recuperar la contraseña invalida las sesiones anteriores.",notification:"Verificación, invitación o recuperación mediante enlaces de un solo uso en la cola de correos."},
    {id:"origen",title:flow.originMode === "casillero" ? "Anticipa tu compra" : "Prepara la recepción",summary:flow.originMode === "casillero" ? "La prealerta identifica la compra; todavía no confirma una caja en bodega." : "El cliente coordina la entrega física; este modo no utiliza prealertas.",client:flow.originMode === "casillero" ? "Registra tienda, tracking, contenido, valor declarado y categoría estimada." : "Prepara su caja y coordina la entrega con el equipo. No hay reserva automática de recolección.",admin:"Identifica al cliente y su casillero antes de recibir físicamente.",system:flow.originMode === "casillero" ? "Crea un código de caja y rechaza tracking duplicado." : "Oculta y bloquea la creación de prealertas en entrega directa.",guard:"La categoría estimada no es la medición final. Empacar es una operación física, no un estado automático.",notification:flow.originMode === "casillero" ? "Registro de prealerta y confirmación al cliente." : "El registro operativo comienza en recepción.",...(flow.originMode === "casillero" ? {box:"pre-alertada" as const} : {})},
    {id:"recepcion",title:"Recibe y valida",summary:"El equipo mide, pesa y confirma la categoría antes de ingresar a bodega.",client:"Consulta el resultado y el código de su caja.",admin:"Selecciona la prealerta si existe, captura medidas y peso; registra el rechazo con motivo cuando no puede aceptarla.",system:`Conserva código, tracking e historial al recibir una prealerta. ${flow.billingMoment === "al-recibir" ? "Emite aquí la factura." : "La factura se genera aquí si se registra la forma de pago; en otro caso, al despachar."}`,
      guard:flow.excessPolicy === "rechazo" ? "La política de excedente se aplica a categorías estándar. Fuera del catálogo permite Carga personalizada con precio acordado." : "No asigna categorías estándar que no admitan las medidas. Fuera del catálogo recibe como Carga personalizada con precio acordado; no rechaza automáticamente.",notification:"Seleccionar una prealerta avisa al cliente; confirmar su recepción genera otro evento y permite imprimir la etiqueta. El rechazo también se notifica.",box:"en-bodega"},
    {id:"envio",title:"Confirma el envío",summary:"El envío agrupa cajas y destinatario. Confirmarlo no despacha el camión.",client:`Elige sus cajas disponibles, destinatario y entrega ${delivery}.`,admin:"Ve las solicitudes confirmadas pendientes de asignación.",system:"Verifica propiedad y disponibilidad de las cajas; conserva una copia del destinatario y dirección para el historial.",guard:"No se pueden seleccionar cajas ajenas, ya asignadas o fuera de bodega. La recepción directa de una caja no crea por sí sola un envío.",notification:"Confirmación del envío con notificación y correo en cola.",box:"en-bodega",shipment:"confirmado"},
    {id:"carga",title:"Organiza la carga",summary:"El equipo asigna el envío completo a una guía máster.",client:"Ve la relación con el camión y sus avances registrados.",admin:"Crea el camión y configura almacenes con fechas de llegada; inicia la carga y escanea cada paquete seleccionando su parada.",system:"Vincula caja, envío y camión; controla capacidad y permite retirar cajas antes del despacho.",guard:"Todas las cajas de un envío deben viajar juntas. La carga incompleta bloquea el despacho.",notification:"Cada escaneo de carga genera una notificación y un correo en cola.",box:"cargada-en-camion",shipment:"confirmado",truck:"cargando"},
    {id:"salida",title:"Despacha el camión",summary:"Aquí comienza el tránsito, por una acción del equipo operativo.",client:"Consulta el avance por código de caja, envío o guía máster.",admin:"Confirma la salida una vez completada la carga.",system:`Cambia las cajas y sus envíos a En tránsito. ${flow.billingMoment === "al-despachar" ? "Factura aquí las cajas aún no facturadas." : "No vuelve a facturar las cajas ya facturadas en recepción."}`,
      guard:"No se despacha un camión vacío ni un envío parcialmente cargado.",notification:"Actualización de tránsito y correo en cola; la factura, si corresponde, aparece en el panel.",box:"en-transito",shipment:"en-transito",truck:"despachado"},
    {id:"frontera",title:"Registra frontera",summary:"El seguimiento refleja hitos registrados, no una ubicación GPS en vivo.",client:"Ve el avance del camión hacia el cruce fronterizo.",admin:"Registra la etapa de frontera desde la guía máster.",system:"Actualiza el camión; cajas y envíos permanecen En tránsito hasta llegar a destino.",guard:"El hito no equivale a un comprobante aduanal ni a despacho aduanero automatizado.",notification:"Actualización del camión con notificación y correo en cola.",box:"en-transito",shipment:"en-transito",truck:"en-frontera"},
    {id:"destino",title:"Llega a destino",summary:"La carga está en destino, todavía no entregada al destinatario.",client:"Consulta que sus cajas están listas para la última etapa.",admin:"El operador del almacén selecciona el camión y escanea cada descarga; el administrador gestiona las entregas.",system:"Cada descarga cambia solo esa caja a En destino. Un envío llega cuando se reciben todas sus cajas; el camión llega cuando se completan todas sus paradas.",guard:"El operador solo recibe en los almacenes asignados: puede consultar contactos autorizados, nunca facturas ni cobros.",notification:"Cada descarga genera una notificación y correo con el mensaje personalizado del almacén.",box:"en-destino",shipment:"en-destino",truck:"en-destino"},
    {id:"entrega",title:"Confirma la entrega",summary:`Recepción física ${delivery}, registrada caja por caja.`,client:"Ve quién recibió y el historial de entrega de sus cajas.",admin:"Después de entregar físicamente, captura el nombre de quien recibe y la nota de verificación.",system:"Marca cada caja entregada; completa el envío únicamente al entregar su última caja.",guard:"No permite entregar antes de llegar a destino ni registrar dos veces la misma entrega. No incluye firma digital.",notification:"Cada entrega genera notificación y correo en cola al cliente.",box:"entregada",shipment:"entregado",truck:"en-destino"},
  ];
}
