import {receptionEmailHtml,receptionEmailText,type ReceptionEmail} from './reception-email-layout';
export type EmailInput = { to: string; subject: string; heading: string; body: string; actionLabel?: string; actionUrl?: string; expiresAt?: string;reception?:ReceptionEmail;receptionPhoto?:{fileId:string;ownerId:string} };
export const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
export function renderEmail(input: EmailInput, siteUrl: string) {
  const e = escapeHtml;
  const actionUrl = input.actionUrl && new URL(input.actionUrl).origin === new URL(siteUrl).origin ? input.actionUrl : undefined;
  return {
    text: `${input.heading}\n\n${input.reception?receptionEmailText(input.reception):input.body}${actionUrl ? `\n\n${input.actionLabel ?? "Continuar"}: ${actionUrl}` : ""}\n\nA&L Trucking Logistics · Tu envío, en buenas manos.\nEste es un correo automático. Nunca te pediremos tu contraseña por correo.`,
    html: `<!doctype html><html lang="es"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>${e(input.subject)}</title></head><body style="margin:0;background:#F8F5F0;color:#1C2B4B;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${e(input.heading)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:40px 16px"><table role="presentation" width="600" style="width:100%;max-width:600px" cellpadding="0" cellspacing="0"><tr><td style="padding:0 0 28px"><img src="${e(siteUrl)}/brand/logoayl.png" width="150" alt="A&amp;L Trucking Logistics" style="display:block;max-width:150px;height:auto"></td></tr><tr><td style="background:#ffffff;border:1px solid #E8E2D9;border-radius:20px;padding:40px 28px"><p style="margin:0 0 20px;font-size:11px;letter-spacing:2px;color:#A8410C;font-weight:700">TU CUENTA · A&amp;L</p><h1 style="margin:0;font-size:32px;line-height:1.15;letter-spacing:-1px">${e(input.heading)}</h1>${input.reception?receptionEmailHtml(input.reception,e):`<p style="margin:24px 0;font-size:16px;line-height:1.8;color:#566075">${e(input.body)}</p>`}${input.receptionPhoto?`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:24px 0"><tr><td><h2 style="margin:0 0 12px;font-size:16px">Foto de recepción</h2><img src="cid:reception-photo" alt="Primera foto registrada en la recepción" width="500" style="display:block;width:100%;max-width:500px;height:auto;border:1px solid #E8E2D9;border-radius:12px"><p style="margin:10px 0 0;font-size:12px;line-height:1.6;color:#697386">Primera foto de esta recepción. También puedes verla en el detalle del paquete desde tu panel.</p></td></tr></table>`:""}${actionUrl ? `<table role="presentation" cellpadding="0" cellspacing="0"><tr><td bgcolor="#C24E12" style="border-radius:12px"><a href="${e(actionUrl)}" style="display:inline-block;padding:18px 26px;color:#ffffff;text-decoration:none;font-size:15px;font-weight:bold">${e(input.actionLabel ?? "Continuar")} &rarr;</a></td></tr></table><p style="margin:24px 0 0;font-size:12px;line-height:1.7;color:#697386">Si el botón no funciona, copia este enlace en tu navegador:<br><a href="${e(actionUrl)}" style="color:#A8410C;word-break:break-all">${e(actionUrl)}</a></p>` : ""}<hr style="border:0;border-top:1px solid #E8E2D9;margin:32px 0 20px"><p style="margin:0;color:#697386;font-size:12px;line-height:1.8">Por tu seguridad, nunca compartas tu contraseña ni este enlace. Si no solicitaste este mensaje, puedes ignorarlo.</p></td></tr><tr><td style="padding:24px 8px;font-size:12px;line-height:1.8;color:#697386">A&amp;L Trucking Logistics<br>Tu envío, en buenas manos.</td></tr></table></td></tr></table></body></html>`,
  };
}
