export const MEXICO_STATES = ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"] as const;

export const POSTAL_CODE_CATALOG: Record<string, { state: string; municipality: string }> = {
  "01000": { state: "Ciudad de México", municipality: "Álvaro Obregón" }, "02000": { state: "Ciudad de México", municipality: "Azcapotzalco" }, "03000": { state: "Ciudad de México", municipality: "Benito Juárez" }, "04000": { state: "Ciudad de México", municipality: "Coyoacán" }, "06000": { state: "Ciudad de México", municipality: "Cuauhtémoc" },
  "20000": { state: "Aguascalientes", municipality: "Aguascalientes" }, "21000": { state: "Baja California", municipality: "Mexicali" }, "22000": { state: "Baja California", municipality: "Tijuana" }, "23000": { state: "Baja California Sur", municipality: "La Paz" }, "24000": { state: "Campeche", municipality: "Campeche" },
  "25000": { state: "Coahuila", municipality: "Saltillo" }, "28000": { state: "Colima", municipality: "Colima" }, "29000": { state: "Chiapas", municipality: "Tuxtla Gutiérrez" }, "31000": { state: "Chihuahua", municipality: "Chihuahua" }, "34000": { state: "Durango", municipality: "Durango" },
  "36000": { state: "Guanajuato", municipality: "Guanajuato" }, "39000": { state: "Guerrero", municipality: "Chilpancingo" }, "42000": { state: "Hidalgo", municipality: "Pachuca" }, "44100": { state: "Jalisco", municipality: "Guadalajara" }, "50000": { state: "Estado de México", municipality: "Toluca" },
  "58000": { state: "Michoacán", municipality: "Morelia" }, "62000": { state: "Morelos", municipality: "Cuernavaca" }, "63000": { state: "Nayarit", municipality: "Tepic" }, "64000": { state: "Nuevo León", municipality: "Monterrey" }, "68000": { state: "Oaxaca", municipality: "Oaxaca de Juárez" },
  "72000": { state: "Puebla", municipality: "Puebla" }, "76000": { state: "Querétaro", municipality: "Querétaro" }, "77000": { state: "Quintana Roo", municipality: "Othón P. Blanco" }, "78000": { state: "San Luis Potosí", municipality: "San Luis Potosí" }, "80000": { state: "Sinaloa", municipality: "Culiacán" },
};
