import type {ReactNode} from 'react';
import type {Box} from '@/lib/types';
import {groupReceptions,receptionConceptSummaries,boxWeightLabel} from '@/lib/utils/reception-display';
import {formatUsd} from '@/lib/utils/format';
import {StatusBadge} from './badge';

export function ReceptionList({boxes,showAmounts=false,heading,selection,pieceLink,actions}:{boxes:Box[];showAmounts?:boolean;heading?:(boxes:Box[])=>ReactNode;selection?:(boxes:Box[])=>ReactNode;pieceLink:(box:Box)=>ReactNode;actions?:(box:Box)=>ReactNode}){
 return <div className="grid min-w-0 gap-4">{groupReceptions(boxes).map(group=>{
  const summaries=receptionConceptSummaries(group.boxes),amount=summaries.reduce((n,c)=>n+c.amountUsd,0);
  const details=<div className="grid gap-2 border-t border-stone-100 pt-3">{group.boxes.map(box=><div key={box.id} className="flex min-w-0 flex-wrap items-center gap-3 rounded-xl bg-stone-50 px-3 py-3">{selection?.([box])}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{pieceLink(box)}{box.receptionGroup&&<span className="text-xs text-navy-400">Pieza {box.receptionGroup.index}/{box.receptionGroup.total}</span>}<StatusBadge status={box.status}/></div><p className="mt-1 text-xs leading-5 text-navy-500">{box.contentsNote??box.categoryName??'Paquete'} · {boxWeightLabel(box)}</p></div>{actions?.(box)}</div>)}</div>;
  return <article key={group.id} className="grid min-w-0 gap-4 rounded-2xl border border-stone-200 bg-white p-4 sm:p-5"><header className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-3">{group.boxes.length>1&&selection?.(group.boxes)}<div><p className="text-[10px] font-semibold uppercase tracking-wider text-navy-400">Recepción · {group.boxes.length} {group.boxes.length===1?'pieza':'piezas'}{group.boxes[0].receptionGroup&&group.boxes.length<group.boxes[0].receptionGroup.total?' visibles de '+group.boxes[0].receptionGroup.total:''}</p><h3 className="mt-1 font-display text-lg font-bold text-navy-950">{group.code}</h3>{heading?.(group.boxes)}</div></div>{showAmounts&&<strong className="text-lg tabular-nums text-navy-950">{formatUsd(amount)}</strong>}</header><div className="grid gap-2">{summaries.map(c=><div key={c.id} className="flex flex-wrap items-start justify-between gap-2 border-l-2 border-orange-200 pl-3"><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{c.count} × {c.description}</p><p className="mt-1 text-xs leading-5 text-navy-500">{c.weight}</p></div>{showAmounts&&<span className="text-sm font-semibold tabular-nums">{formatUsd(c.amountUsd)}</span>}</div>)}</div>{group.boxes.length>1?<details className="group"><summary className="cursor-pointer py-1 text-sm font-semibold text-orange-700">Ver {group.boxes.length} piezas y sus estados</summary><div className="mt-3">{details}</div></details>:details}</article>;
 })}</div>;
}
